/* generated by scripts/bundle-api.mjs — do not edit */

// src/lib/scanner/rules.ts
var SCAN_CHAINS = /* @__PURE__ */ new Set(["solana", "base", "bsc"]);
var DROP_SYMBOLS = /* @__PURE__ */ new Set(["SOL", "WSOL", "USDC", "USDT", "ETH", "WETH", "BNB", "WBNB"]);
function droppedSymbol(symbol) {
  return DROP_SYMBOLS.has(symbol.trim().toUpperCase());
}

// src/lib/agent/jupiter.ts
var USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
var MAX_IMPACT_PCT = 3;
function base(env) {
  return (env.JUPITER_API_URL || (env.JUPITER_API_KEY ? "https://api.jup.ag/swap/v1" : "https://lite-api.jup.ag/swap/v1")).replace(/\/$/, "");
}
function headers(env) {
  return {
    accept: "application/json",
    "content-type": "application/json",
    ...env.JUPITER_API_KEY ? { "x-api-key": env.JUPITER_API_KEY } : {}
  };
}
async function readJson(res, what) {
  const text = await res.text();
  let body = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
  }
  if (!res.ok || !body) throw new Error(`Jupiter ${what} ${res.status}: ${body?.error || text.slice(0, 160)}`);
  return body;
}
async function quoteExactIn(input, env, fetchFn = fetch) {
  const q = new URLSearchParams({
    inputMint: input.inputMint,
    outputMint: input.outputMint,
    amount: input.amount,
    slippageBps: String(input.slippageBps),
    swapMode: "ExactIn"
  });
  const res = await fetchFn(`${base(env)}/quote?${q}`, { headers: headers(env), signal: AbortSignal.timeout(1e4) });
  return readJson(res, "quote");
}
function impactPct(quote) {
  return Math.abs(Number(quote.priceImpactPct) || 0) * 100;
}
async function buildSwap(quote, user, env, fetchFn = fetch) {
  const res = await fetchFn(`${base(env)}/swap`, {
    method: "POST",
    headers: headers(env),
    body: JSON.stringify({
      quoteResponse: quote,
      userPublicKey: user,
      wrapAndUnwrapSol: false,
      dynamicComputeUnitLimit: true,
      prioritizationFeeLamports: { priorityLevelWithMaxLamports: { maxLamports: 2e5, priorityLevel: "high" } }
    }),
    signal: AbortSignal.timeout(15e3)
  });
  return readJson(res, "swap");
}

// src/lib/agent/chain.ts
var TOKEN_PROGRAMS = ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"];
function rpcUrls(env) {
  if (env.SOLANA_RPC_URL) return [env.SOLANA_RPC_URL];
  if (env.HELIUS_API_KEY) return [`https://mainnet.helius-rpc.com/?api-key=${env.HELIUS_API_KEY}`];
  return ["https://api.mainnet-beta.solana.com", "https://solana-rpc.publicnode.com"];
}
async function rpc(urls, method, params, fetchFn = fetch) {
  let last = new Error("no Solana RPC");
  for (const url of urls) {
    try {
      return await rpcOnce(url, method, params, fetchFn);
    } catch (err) {
      last = err;
    }
  }
  throw last;
}
async function rpcOnce(url, method, params, fetchFn) {
  const res = await fetchFn(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
    signal: AbortSignal.timeout(15e3)
  });
  const body = await res.json().catch(() => ({}));
  if (body.error) {
    const err = body.error.data?.err;
    const log = body.error.data?.logs?.filter((l) => /error|failed|insufficient/i.test(l)).slice(-1)[0];
    const detail = [err != null ? JSON.stringify(err) : "", log || ""].filter(Boolean).join(" \u2014 ");
    throw new Error(`${body.error.message || `${method} failed`}${detail ? `: ${detail}` : ""}`);
  }
  if (!res.ok) throw new Error(`${method} HTTP ${res.status}`);
  return body.result;
}
async function walletBalances(urls, owner, fetchFn = fetch) {
  const [lamports, ...programs] = await Promise.all([
    rpc(urls, "getBalance", [owner, { commitment: "confirmed" }], fetchFn),
    ...TOKEN_PROGRAMS.map(
      (programId) => rpc(
        urls,
        "getTokenAccountsByOwner",
        [owner, { programId }, { encoding: "jsonParsed", commitment: "confirmed" }],
        fetchFn
      )
    )
  ]);
  const byMint = /* @__PURE__ */ new Map();
  for (const program of programs) {
    for (const acc of program.value) {
      const info = acc.account.data.parsed.info;
      const prev = byMint.get(info.mint);
      const raw = (BigInt(prev?.raw ?? "0") + BigInt(info.tokenAmount.amount)).toString();
      byMint.set(info.mint, { mint: info.mint, raw, ui: (prev?.ui ?? 0) + (info.tokenAmount.uiAmount ?? 0) });
    }
  }
  const tokens = [...byMint.values()].filter((t) => t.raw !== "0");
  return {
    sol: lamports.value / 1e9,
    usdc: byMint.get(USDC_MINT)?.ui ?? 0,
    tokens
  };
}
async function sendTransaction(urls, base64, fetchFn = fetch) {
  return rpc(
    urls,
    "sendTransaction",
    [base64, { encoding: "base64", skipPreflight: false, preflightCommitment: "confirmed", maxRetries: 0 }],
    fetchFn
  );
}
async function waitForSignature(urls, signature, lastValidBlockHeight, timeoutMs, fetchFn = fetch) {
  const until = Date.now() + timeoutMs;
  while (Date.now() < until) {
    const st = await rpc(
      urls,
      "getSignatureStatuses",
      [[signature]],
      fetchFn
    ).catch(() => null);
    const s = st?.value?.[0];
    if (s?.err) return { state: "failed", error: `on-chain error ${JSON.stringify(s.err)}` };
    if (s && (s.confirmationStatus === "confirmed" || s.confirmationStatus === "finalized")) return { state: "confirmed" };
    const height = await rpc(urls, "getBlockHeight", [{ commitment: "confirmed" }], fetchFn).catch(() => 0);
    if (!s && height > lastValidBlockHeight) return { state: "failed", error: "blockhash expired before the swap landed" };
    await new Promise((r) => setTimeout(r, 1500));
  }
  return { state: "unknown" };
}

// src/lib/agent/keys.ts
import { createPrivateKey, createPublicKey, generateKeyPairSync, sign } from "node:crypto";
var ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
var PKCS8_ED25519 = Buffer.from("302e020100300506032b657004220420", "hex");
function base58Encode(bytes) {
  let n = 0n;
  for (const b of bytes) n = n << 8n | BigInt(b);
  let out = "";
  while (n > 0n) {
    out = ALPHABET[Number(n % 58n)] + out;
    n /= 58n;
  }
  for (const b of bytes) {
    if (b !== 0) break;
    out = "1" + out;
  }
  return out;
}
function base58Decode(text) {
  let n = 0n;
  for (const ch of text) {
    const i = ALPHABET.indexOf(ch);
    if (i < 0) throw new Error("not base58");
    n = n * 58n + BigInt(i);
  }
  const bytes = [];
  while (n > 0n) {
    bytes.unshift(Number(n & 0xffn));
    n >>= 8n;
  }
  for (const ch of text) {
    if (ch !== "1") break;
    bytes.unshift(0);
  }
  return Uint8Array.from(bytes);
}
function fromSeed(seed) {
  const key2 = createPrivateKey({
    key: Buffer.concat([PKCS8_ED25519, Buffer.from(seed)]),
    format: "der",
    type: "pkcs8"
  });
  const spki = createPublicKey(key2).export({ format: "der", type: "spki" });
  const publicKey = Uint8Array.from(spki.subarray(spki.length - 32));
  return {
    address: base58Encode(publicKey),
    publicKey,
    sign: (message) => Uint8Array.from(sign(null, Buffer.from(message), key2))
  };
}
function loadSigner(secret) {
  const raw = (secret || "").trim();
  if (!raw) throw new Error("AGENT_SIGNER is not set");
  const bytes = raw.startsWith("[") ? Uint8Array.from(JSON.parse(raw)) : base58Decode(raw);
  if (bytes.length !== 64 && bytes.length !== 32) throw new Error("AGENT_SIGNER must be a 64-byte Solana secret");
  const signer = fromSeed(bytes.subarray(0, 32));
  if (bytes.length === 64 && base58Encode(bytes.subarray(32)) !== signer.address) {
    throw new Error("AGENT_SIGNER public half does not match its seed");
  }
  return signer;
}

// src/lib/agent/tx.ts
var SWAP_PROGRAMS = /* @__PURE__ */ new Set([
  "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
  "ComputeBudget111111111111111111111111111111",
  "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
  "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
]);
function shortVec(bytes, at) {
  let value = 0;
  let size = 0;
  for (; ; ) {
    const b = bytes[at + size];
    value |= (b & 127) << 7 * size;
    size += 1;
    if ((b & 128) === 0) return [value, size];
    if (size > 3) throw new Error("bad shortvec");
  }
}
function parseTransaction(bytes) {
  const [signatureCount, sigLen] = shortVec(bytes, 0);
  const messageOffset = sigLen + signatureCount * 64;
  let at = messageOffset;
  if (bytes[at] & 128) {
    if ((bytes[at] & 127) !== 0) throw new Error("unsupported transaction version");
    at += 1;
  }
  const requiredSigners = bytes[at];
  at += 3;
  const [keyCount, keyLen] = shortVec(bytes, at);
  at += keyLen;
  const accountKeys = [];
  for (let i = 0; i < keyCount; i += 1) {
    accountKeys.push(base58Encode(bytes.subarray(at, at + 32)));
    at += 32;
  }
  at += 32;
  const [ixCount, ixLen] = shortVec(bytes, at);
  at += ixLen;
  const programs = [];
  for (let i = 0; i < ixCount; i += 1) {
    const programIndex = bytes[at];
    at += 1;
    const [accLen, accSize] = shortVec(bytes, at);
    at += accSize + accLen;
    const [dataLen, dataSize] = shortVec(bytes, at);
    at += dataSize + dataLen;
    const program = accountKeys[programIndex];
    if (!program) throw new Error("instruction program is not a static key");
    programs.push(program);
  }
  return { signatureCount, messageOffset, requiredSigners, accountKeys, programs };
}
function signSwapTransaction(base64, signer) {
  const bytes = Uint8Array.from(Buffer.from(base64, "base64"));
  const tx = parseTransaction(bytes);
  if (tx.requiredSigners !== 1 || tx.signatureCount !== 1) throw new Error("swap must have exactly one signer");
  if (tx.accountKeys[0] !== signer.address) throw new Error("swap fee payer is not the agent wallet");
  const stray = tx.programs.find((p) => !SWAP_PROGRAMS.has(p));
  if (stray) throw new Error(`swap calls a non-swap program ${stray}`);
  if (!tx.programs.includes("JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4")) throw new Error("not a Jupiter swap");
  const sig = signer.sign(bytes.subarray(tx.messageOffset));
  const out = Uint8Array.from(bytes);
  out.set(sig, 1);
  return { signed: Buffer.from(out).toString("base64"), signature: base58Encode(sig) };
}

// src/lib/agent/agent.ts
var ATTEMPTS = 2;
var LAND_WAIT_MS = 22e3;
var AgentError = class extends Error {
  status;
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
function publicIntent(row) {
  const { playSnapshot: _snap, ...rest } = row;
  return rest;
}
async function bootWallet(deps2) {
  return deps2.store.bootWallet(deps2.signer.address, deps2.env.AGENT_WITHDRAW?.trim() || null);
}
async function confirmIntent(deps2, intentId) {
  if (!intentId) throw new AgentError(400, "intentId is required");
  const wallet = await bootWallet(deps2);
  const intent = await deps2.store.intent(intentId);
  if (!intent) throw new AgentError(404, "no such intent");
  if (intent.status !== "pending") throw new AgentError(409, `intent is ${intent.status}, not pending`);
  if (!intent.expiresAt || Date.parse(intent.expiresAt) <= Date.now()) {
    await deps2.store.expirePending();
    throw new AgentError(409, "intent expired");
  }
  const claimed = await deps2.store.claimPending(intentId);
  if (!claimed) throw new AgentError(409, "intent expired or already confirming");
  if (intent.side === "buy" && await deps2.store.position(intent.mint)) {
    await deps2.store.finishIntent(intentId, { status: "failed", error: "agent already holds this mint" });
    return publicIntent(await deps2.store.intent(intentId));
  }
  const q = intent.playSnapshot.quote;
  const errors = [];
  let sent = null;
  for (let attempt = 1; attempt <= ATTEMPTS; attempt += 1) {
    try {
      const quote = await quoteExactIn(
        { inputMint: q.inputMint, outputMint: q.outputMint, amount: q.amount, slippageBps: q.slippageBps },
        deps2.env,
        deps2.fetchFn
      );
      const impact = impactPct(quote);
      if (impact > MAX_IMPACT_PCT) throw new Error(`price impact ${impact.toFixed(2)}% over 3% at confirm`);
      const swap = await buildSwap(quote, wallet.address, deps2.env, deps2.fetchFn);
      const signed = signSwapTransaction(swap.swapTransaction, deps2.signer);
      await sendTransaction(deps2.rpcUrls, signed.signed, deps2.fetchFn);
      const signature = signed.signature;
      sent = signature;
      const landed = await waitForSignature(deps2.rpcUrls, signature, swap.lastValidBlockHeight, LAND_WAIT_MS, deps2.fetchFn);
      if (landed.state === "unknown") {
        await deps2.store.finishIntent(intentId, {
          status: "failed",
          signature,
          error: `sent ${signature} but not confirmed in ${LAND_WAIT_MS / 1e3}s; not retried so it cannot fill twice`
        });
        return publicIntent(await deps2.store.intent(intentId));
      }
      if (landed.state === "failed") throw new Error(landed.error);
      if (intent.side === "buy") {
        const qty = await walletBalances(deps2.rpcUrls, wallet.address, deps2.fetchFn).then((b) => b.tokens.find((t) => t.mint === intent.mint)?.raw).catch(() => void 0);
        await deps2.store.upsertBuy({
          mint: intent.mint,
          symbol: intent.symbol,
          qty: qty ?? quote.outAmount,
          costUsd: intent.sizeUsd ?? 0
        });
      } else {
        await deps2.store.closePosition(intent.mint);
      }
      await deps2.store.finishIntent(intentId, { status: "signed", signature, error: null });
      return publicIntent(await deps2.store.intent(intentId));
    } catch (err) {
      errors.push(`attempt ${attempt}: ${err instanceof Error ? err.message : String(err)}`);
      if (attempt === ATTEMPTS) {
        await deps2.store.finishIntent(intentId, { status: "failed", signature: sent, error: errors.join(" | ") });
      }
    }
  }
  return publicIntent(await deps2.store.intent(intentId));
}

// src/lib/agent/store.ts
import pg from "pg";

// src/types/agent.ts
var CONFIRMING = "confirm in progress";

// src/lib/agent/store.ts
var SCHEMA_SQL = `
create table if not exists agent_wallet (
  id text primary key,
  address text not null unique,
  chain text not null default 'solana',
  cap_usd numeric not null default 500,
  withdraw_address text,
  created_at timestamptz not null default now()
);

create table if not exists agent_intent (
  id text primary key,
  handle text not null,
  mint text not null,
  symbol text,
  side text not null check (side in ('buy', 'sell')),
  status text not null check (status in ('rejected', 'pending', 'expired', 'signed', 'failed')),
  reason text,
  reject_reason text,
  size_usd numeric,
  quote_out text,
  price_impact_pct numeric,
  play_snapshot jsonb not null,
  expires_at timestamptz,
  confirmed_at timestamptz,
  signature text,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists agent_intent_created_at_idx on agent_intent (created_at desc);

create table if not exists agent_position (
  mint text primary key,
  symbol text,
  qty text not null,
  cost_usd numeric not null,
  opened_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
`;
var WALLET_ID = "agent";
var num = (v) => v == null ? null : Number(v);
var iso = (v) => v == null ? null : new Date(v).toISOString();
function walletRow(r) {
  return {
    id: r.id,
    address: r.address,
    chain: r.chain,
    capUsd: Number(r.cap_usd),
    withdrawAddress: r.withdraw_address ?? null,
    createdAt: iso(r.created_at)
  };
}
function intentRow(r) {
  return {
    id: r.id,
    handle: r.handle,
    mint: r.mint,
    symbol: r.symbol ?? null,
    side: r.side,
    status: r.status,
    reason: r.reason ?? null,
    rejectReason: r.reject_reason ?? null,
    sizeUsd: num(r.size_usd),
    quoteOut: r.quote_out ?? null,
    priceImpactPct: num(r.price_impact_pct),
    playSnapshot: r.play_snapshot,
    expiresAt: iso(r.expires_at),
    confirmedAt: iso(r.confirmed_at),
    signature: r.signature ?? null,
    error: r.error ?? null,
    createdAt: iso(r.created_at)
  };
}
function positionRow(r) {
  return {
    mint: r.mint,
    symbol: r.symbol ?? null,
    qty: r.qty,
    costUsd: Number(r.cost_usd),
    openedAt: iso(r.opened_at),
    updatedAt: iso(r.updated_at)
  };
}
var pool = null;
var poolUrl = "";
var schemaReady = null;
function databaseUrl(env) {
  return env.DATABASE_URL || env.POSTGRES_URL || "";
}
function pgStore(url) {
  if (!pool || poolUrl !== url) {
    pool = new pg.Pool({ connectionString: url, max: 3, idleTimeoutMillis: 1e4 });
    poolUrl = url;
    schemaReady = null;
  }
  const db = pool;
  const ready = () => schemaReady ??= db.query(SCHEMA_SQL).then(() => void 0);
  const q = async (text, values = []) => {
    await ready();
    return (await db.query(text, values)).rows;
  };
  return {
    async bootWallet(address, withdrawAddress) {
      await q(
        `insert into agent_wallet (id, address, withdraw_address) values ($1, $2, $3) on conflict (id) do nothing`,
        [WALLET_ID, address, withdrawAddress]
      );
      const rows = await q(
        `update agent_wallet set withdraw_address = coalesce($2, withdraw_address) where id = $1 returning *`,
        [WALLET_ID, withdrawAddress]
      );
      const row = walletRow(rows[0]);
      if (row.address !== address) {
        throw new Error(`agent_wallet holds ${row.address}; AGENT_SIGNER is ${address}. One agent wallet only.`);
      }
      return row;
    },
    async positions() {
      return (await q(`select * from agent_position order by opened_at`)).map(positionRow);
    },
    async position(mint) {
      const rows = await q(`select * from agent_position where mint = $1`, [mint]);
      return rows[0] ? positionRow(rows[0]) : null;
    },
    async insertIntent(row) {
      const rows = await q(
        `insert into agent_intent
          (id, handle, mint, symbol, side, status, reason, reject_reason, size_usd, quote_out, price_impact_pct, play_snapshot, expires_at)
         values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,
           case when $13::int is null then null else now() + make_interval(secs => $13::int) end)
         returning *`,
        [
          row.id,
          row.handle,
          row.mint,
          row.symbol,
          row.side,
          row.status,
          row.reason,
          row.rejectReason,
          row.sizeUsd,
          row.quoteOut,
          row.priceImpactPct,
          JSON.stringify(row.playSnapshot),
          row.expiresInSec
        ]
      );
      return intentRow(rows[0]);
    },
    async intent(id) {
      const rows = await q(`select * from agent_intent where id = $1`, [id]);
      return rows[0] ? intentRow(rows[0]) : null;
    },
    async recentIntents(limit) {
      return (await q(`select * from agent_intent order by created_at desc limit $1`, [limit])).map(intentRow);
    },
    async expirePending() {
      await q(`update agent_intent set status = 'expired' where status = 'pending' and expires_at <= now()`);
    },
    async claimPending(id) {
      const rows = await q(
        `update agent_intent set status = 'failed', error = $2
         where id = $1 and status = 'pending' and expires_at > now() returning *`,
        [id, CONFIRMING]
      );
      return rows[0] ? intentRow(rows[0]) : null;
    },
    async finishIntent(id, patch) {
      await q(
        `update agent_intent set status = $2, signature = coalesce($3, signature), error = $4,
           confirmed_at = case when $2 = 'signed' then now() else confirmed_at end
         where id = $1`,
        [id, patch.status, patch.signature ?? null, patch.error ?? null]
      );
    },
    async upsertBuy(input) {
      await q(
        `insert into agent_position (mint, symbol, qty, cost_usd) values ($1, $2, $3, $4)
         on conflict (mint) do update set qty = excluded.qty, symbol = coalesce(excluded.symbol, agent_position.symbol),
           cost_usd = agent_position.cost_usd + excluded.cost_usd, updated_at = now()`,
        [input.mint, input.symbol, input.qty, input.costUsd]
      );
    },
    async closePosition(mint) {
      await q(`delete from agent_position where mint = $1`, [mint]);
    }
  };
}

// src/lib/scanner/tape.ts
var DEX = "https://api.dexscreener.com";
var GECKO = "https://api.geckoterminal.com/api/v2";
var TAPE_TTL_MS = 12e3;
var PAIR_TTL_MS = 12e3;
var PAIR_BATCH = 30;
var PAIR_KEEP_MS = 10 * 6e4;
var cache = null;
var inflight = null;
var pairs = /* @__PURE__ */ new Map();
async function getJson(url, fetchFn, timeoutMs = 8e3) {
  const res = await fetchFn(url, {
    headers: { accept: "application/json" },
    signal: AbortSignal.timeout(timeoutMs)
  });
  if (!res.ok) throw new Error(`${new URL(url).host} ${res.status}`);
  return await res.json();
}
function key(chain, mint) {
  return `${chain}:${mint.startsWith("0x") ? mint.toLowerCase() : mint}`;
}
function num2(v) {
  const n = typeof v === "string" ? Number(v) : typeof v === "number" ? v : NaN;
  return Number.isFinite(n) ? n : 0;
}
function numOrNull(v) {
  if (v == null || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}
function positiveOrNull(v) {
  const n = numOrNull(v);
  return n != null && n > 0 ? n : null;
}
function social(pair, type) {
  return pair.info?.socials?.find((x) => x.type?.toLowerCase() === type && x.url)?.url;
}
function rowFromDexPair(pair, sources, now = Date.now()) {
  const mint = pair.baseToken?.address;
  const chain = pair.chainId || "";
  if (!mint || !SCAN_CHAINS.has(chain)) return null;
  return {
    chain,
    mint,
    symbol: pair.baseToken?.symbol || "?",
    name: pair.baseToken?.name || "",
    dexId: pair.dexId || "",
    quoteSymbol: pair.quoteToken?.symbol || "",
    liquidityUsd: num2(pair.liquidity?.usd),
    volume1hUsd: num2(pair.volume?.h1),
    marketCapUsd: positiveOrNull(pair.marketCap),
    fdvUsd: positiveOrNull(pair.fdv),
    launchedAt: pair.pairCreatedAt ? new Date(pair.pairCreatedAt).toISOString() : null,
    change5mPct: numOrNull(pair.priceChange?.m5),
    change1hPct: numOrNull(pair.priceChange?.h1),
    change6hPct: numOrNull(pair.priceChange?.h6),
    buys1h: numOrNull(pair.txns?.h1?.buys),
    sells1h: numOrNull(pair.txns?.h1?.sells),
    ageHours: pair.pairCreatedAt ? Math.max(0, (now - pair.pairCreatedAt) / 36e5) : null,
    pairUrl: pair.url || `https://dexscreener.com/${chain}/${mint}`,
    website: pair.info?.websites?.find((w) => w.url)?.url,
    twitter: social(pair, "twitter"),
    telegram: social(pair, "telegram"),
    sources: [...sources]
  };
}
function rowFromGeckoPool(pool2, source, now = Date.now()) {
  const a = pool2.attributes;
  const baseId = pool2.relationships?.base_token?.data?.id || "";
  if (!a || !baseId.startsWith("solana_")) return null;
  const [base2 = "?", quote = ""] = (a.name || "").split(" / ");
  const created = a.pool_created_at ? Date.parse(a.pool_created_at) : NaN;
  return {
    chain: "solana",
    mint: baseId.slice("solana_".length),
    symbol: base2.trim(),
    name: base2.trim(),
    dexId: pool2.relationships?.dex?.data?.id || "",
    quoteSymbol: quote.trim(),
    liquidityUsd: num2(a.reserve_in_usd),
    volume1hUsd: num2(a.volume_usd?.h1),
    marketCapUsd: positiveOrNull(a.market_cap_usd),
    fdvUsd: positiveOrNull(a.fdv_usd),
    launchedAt: Number.isFinite(created) ? new Date(created).toISOString() : null,
    change5mPct: numOrNull(a.price_change_percentage?.m5),
    change1hPct: numOrNull(a.price_change_percentage?.h1),
    change6hPct: numOrNull(a.price_change_percentage?.h6),
    buys1h: numOrNull(a.transactions?.h1?.buys),
    sells1h: numOrNull(a.transactions?.h1?.sells),
    ageHours: Number.isFinite(created) ? Math.max(0, (now - created) / 36e5) : null,
    pairUrl: `https://www.geckoterminal.com/solana/pools/${a.address || ""}`,
    sources: [source]
  };
}
function bestPairs(list) {
  const out = /* @__PURE__ */ new Map();
  for (const p of list) {
    const mint = p.baseToken?.address;
    if (!mint || !p.chainId) continue;
    const k = key(p.chainId, mint);
    const prev = out.get(k);
    if (!prev || num2(p.liquidity?.usd) > num2(prev.liquidity?.usd)) out.set(k, p);
  }
  return out;
}
function pickPairBatch(keys, filled, now, cap = PAIR_BATCH) {
  const fresh = keys.filter((k) => !filled.has(k));
  const stale = keys.filter((k) => filled.has(k) && now - filled.get(k).at >= PAIR_TTL_MS).sort((a, b) => filled.get(a).at - filled.get(b).at);
  return [.../* @__PURE__ */ new Set([...fresh, ...stale])].slice(0, cap);
}
async function loadTape(fetchFn, now) {
  const warnings = [];
  const settle = async (label, p, empty) => {
    try {
      return await p;
    } catch (err) {
      warnings.push(`${label}: ${err instanceof Error ? err.message : "failed"}`);
      return empty;
    }
  };
  const [boosts, profiles, fresh, trending] = await Promise.all([
    settle("Dex boosts", getJson(`${DEX}/token-boosts/latest/v1`, fetchFn), []),
    settle("Dex profiles", getJson(`${DEX}/token-profiles/latest/v1`, fetchFn), []),
    settle(
      "Gecko new pools",
      getJson(`${GECKO}/networks/solana/new_pools?page=1`, fetchFn),
      { data: [] }
    ),
    settle(
      "Gecko trending",
      getJson(`${GECKO}/networks/solana/trending_pools?duration=1h`, fetchFn),
      { data: [] }
    )
  ]);
  const listed = /* @__PURE__ */ new Map();
  const add = (chain, mint, source) => {
    if (!SCAN_CHAINS.has(chain)) return;
    const k = key(chain, mint);
    const row = listed.get(k) || { chain, mint, sources: [] };
    if (!row.sources.includes(source)) row.sources.push(source);
    listed.set(k, row);
  };
  for (const it of Array.isArray(boosts) ? boosts : []) {
    if (it.chainId && it.tokenAddress) add(it.chainId, it.tokenAddress, "dex-boost");
  }
  for (const it of Array.isArray(profiles) ? profiles : []) {
    if (it.chainId && it.tokenAddress) add(it.chainId, it.tokenAddress, "dex-profile");
  }
  const geckoRows = /* @__PURE__ */ new Map();
  for (const pool2 of fresh.data || []) {
    const row = rowFromGeckoPool(pool2, "gecko-new", now);
    if (!row) continue;
    const k = key(row.chain, row.mint);
    if (!geckoRows.has(k)) geckoRows.set(k, row);
    add(row.chain, row.mint, "gecko-new");
  }
  const trendingKeys = /* @__PURE__ */ new Set();
  for (const pool2 of trending.data || []) {
    const row = rowFromGeckoPool(pool2, "gecko-trending", now);
    if (row) trendingKeys.add(key(row.chain, row.mint));
  }
  const batch = pickPairBatch([...listed.keys()], pairs, now);
  const byChain = /* @__PURE__ */ new Map();
  for (const k of batch) {
    const it = listed.get(k);
    byChain.set(it.chain, [...byChain.get(it.chain) || [], it.mint]);
  }
  const fetched = await Promise.all(
    [...byChain.entries()].map(
      ([chain, mints]) => settle(`Dex pairs ${chain}`, getJson(`${DEX}/tokens/v1/${chain}/${mints.join(",")}`, fetchFn), [])
    )
  );
  for (const [k, pair] of bestPairs(fetched.flat().filter(Boolean))) pairs.set(k, { at: now, pair });
  for (const [k, v] of pairs) if (now - v.at > PAIR_KEEP_MS) pairs.delete(k);
  const rows = [];
  for (const [k, it] of listed) {
    const sources = trendingKeys.has(k) ? [...it.sources, "gecko-trending"] : it.sources;
    const pair = pairs.get(k)?.pair;
    const fallback = geckoRows.get(k);
    const row = pair ? rowFromDexPair(pair, sources, now) : fallback ? { ...fallback, sources } : null;
    if (row && !droppedSymbol(row.symbol)) rows.push(row);
  }
  return { rows, warnings, fetchedAt: now };
}
async function fetchTape(fetchFn = fetch, now = Date.now()) {
  if (cache && now - cache.fetchedAt < TAPE_TTL_MS) return cache;
  if (!inflight) {
    inflight = loadTape(fetchFn, now).then((result) => {
      if (result.rows.length) cache = result;
      return result;
    }).finally(() => {
      inflight = null;
    });
  }
  return inflight;
}

// server/vercel-agent.ts
function json(res, status, body) {
  res.setHeader("content-type", "application/json; charset=utf-8");
  res.setHeader("cache-control", "no-store");
  res.status(status).json(body);
}
function readBody(req) {
  const raw = req.body;
  try {
    if (typeof raw === "string") return raw ? JSON.parse(raw) : {};
    if (Buffer.isBuffer(raw)) return JSON.parse(raw.toString("utf8"));
  } catch {
    throw new AgentError(400, "body must be JSON");
  }
  return raw && typeof raw === "object" ? raw : {};
}
function deps(env) {
  const url = databaseUrl(env);
  const missing = [!url && "DATABASE_URL", !env.AGENT_SIGNER && "AGENT_SIGNER"].filter(Boolean);
  if (missing.length) throw new AgentError(503, `agent wallet not set up: ${missing.join(" and ")} missing in server env`);
  return {
    store: pgStore(url),
    signer: loadSigner(env.AGENT_SIGNER),
    rpcUrls: rpcUrls(env),
    env: { JUPITER_API_URL: env.JUPITER_API_URL, JUPITER_API_KEY: env.JUPITER_API_KEY, AGENT_WITHDRAW: env.AGENT_WITHDRAW },
    tape: fetchTape
  };
}
async function run(res, work) {
  try {
    json(res, 200, await work());
  } catch (err) {
    if (err instanceof AgentError) {
      json(res, err.status, { error: err.status === 503 ? "not_configured" : "rejected", message: err.message });
      return;
    }
    json(res, 502, { error: "agent", message: err instanceof Error ? err.message : "agent route failed" });
  }
}
function only(method, req, res) {
  if (req.method === "OPTIONS") {
    res.status(204).end();
    return false;
  }
  if (req.method !== method) {
    json(res, 405, { error: "method", message: `${method} only` });
    return false;
  }
  return true;
}
async function confirmHandler(req, res, env = process.env) {
  if (!only("POST", req, res)) return;
  await run(res, () => confirmIntent(deps(env), String(readBody(req).intentId ?? "")));
}
export {
  confirmHandler as default
};
