/* generated by scripts/bundle-api.mjs — do not edit */

// src/lib/ai/runChat.ts
import { generateText } from "ai";
import { createOpenAI } from "@ai-sdk/openai";

// src/lib/ops/rotation.ts
var byLaunchpad = (row) => [
  { key: row.launchpadId || "unknown", label: row.launchpad || "Unknown" }
];
var byNarrative = (row) => {
  const tags = row.narratives?.length ? row.narratives : ["Untagged"];
  return tags.map((t) => ({ key: t, label: t }));
};
function rollup(open, closed, keyer) {
  const rows = /* @__PURE__ */ new Map();
  const get = (key, label) => {
    const hit = rows.get(key);
    if (hit) return hit;
    const fresh = {
      key,
      label,
      openNames: 0,
      sizeUsd: 0,
      unrealizedUsd: 0,
      pnl24hUsd: 0,
      move24hPct: null,
      realizedUsd: 0,
      closes: 0,
      wins: 0,
      totalPnlUsd: 0,
      dripPerDayUsd: 0,
      symbols: [],
      moveWeight: 0,
      moveSum: 0
    };
    rows.set(key, fresh);
    return fresh;
  };
  for (const p of open) {
    for (const { key, label } of keyer(p)) {
      const r = get(key, label);
      r.openNames += 1;
      r.sizeUsd += p.sizeUsd;
      r.unrealizedUsd += p.hasCostBasis ? p.unrealizedPnl : p.pnl24hUsd ?? 0;
      r.pnl24hUsd += p.pnl24hUsd ?? 0;
      if (p.strategy !== "drip-reward") r.dripPerDayUsd += p.dripPerDayUsd ?? 0;
      if (p.change24hPct != null && p.sizeUsd > 0) {
        r.moveSum += p.change24hPct * p.sizeUsd;
        r.moveWeight += p.sizeUsd;
      }
      if (!r.symbols.includes(p.symbol)) r.symbols.push(p.symbol);
    }
  }
  for (const t of closed) {
    for (const { key, label } of keyer(t)) {
      const r = get(key, label);
      r.realizedUsd += t.realizedPnl;
      r.closes += 1;
      if (t.realizedPnl > 0) r.wins += 1;
      if (!r.symbols.includes(t.symbol)) r.symbols.push(t.symbol);
    }
  }
  return [...rows.values()].map(({ moveWeight, moveSum, ...r }) => ({
    ...r,
    move24hPct: moveWeight > 0 ? moveSum / moveWeight : null,
    totalPnlUsd: r.unrealizedUsd + r.realizedUsd
  })).sort((a, b) => b.totalPnlUsd - a.totalPnlUsd);
}
function launchpadRotation(snap) {
  return rollup(snap.openPositions, snap.closedTrades, byLaunchpad);
}
function narrativeRotation(snap) {
  return rollup(snap.openPositions, snap.closedTrades, byNarrative);
}

// src/lib/ai/bookContext.ts
function compactBook(snap) {
  const s = snap.summary;
  const lines = [
    `Handle: @${snap.handle || "unknown"} (${snap.displayName || "n/a"})`,
    `Equity: ${n(s.totalEquity)} | Cash: ${n(s.cashUsd)} (${pct(s.cashUsd, s.totalEquity)}) | Open: ${n(s.openPositionsValue)}`,
    `Unrealized: ${n(s.unrealizedPnl)} | Realized: ${s.realizedPnlAllTime == null ? "n/a" : n(s.realizedPnlAllTime)} | 24h: ${snap.pnlWindows.h24 == null ? "n/a" : n(snap.pnlWindows.h24)}`,
    `Volume: ${s.volumeUsd == null ? "n/a" : n(s.volumeUsd)} | FOMO trades: ${s.totalTrades} captured closes: ${s.closedTradesCaptured}`,
    `Drawdown: ${s.currentDrawdownPct.toFixed(1)}% from peak ${n(s.peakEquity)} | Rank: ${s.leaderboardRank ?? "n/a"} | Followers: ${s.followers}`,
    `Wallets: SOL ${snap.wallets.solana || "\u2014"} | EVM ${snap.wallets.evm || "\u2014"}`,
    `Sources: fomo=${snap.source.fomo} onchain=${snap.source.onchain} at ${snap.source.fetchedAt}`
  ];
  if (snap.source.warnings.length) lines.push(`Warnings: ${snap.source.warnings.join(" | ")}`);
  lines.push("Open names (size, 24h, unrealized, basis, chain, launchpad, narratives, paired vs):");
  for (const p of snap.openPositions.slice(0, 16)) {
    lines.push(
      `- ${p.symbol} ${n(p.sizeUsd)} 24h=${p.change24hPct == null ? "n/a" : p.change24hPct.toFixed(1) + "%"} u=${n(p.unrealizedPnl)} basis=${p.hasCostBasis ? "yes" : "no"} ${p.chain} pad=${p.launchpad || "?"} story=${(p.narratives || []).join("/") || "?"}${p.quoteSymbol ? ` vs=${p.quoteSymbol}` : ""}${p.strategy && p.strategy !== "trade" ? ` strategy=${p.strategy}${p.dripPays ? ` pays=${p.dripPays}` : ""}${p.dripFrom?.length ? ` from=${p.dripFrom.join("/")}` : ""}${p.dripPerDayUsd ? ` drip/day~${n(p.dripPerDayUsd)}` : ""}` : ""}${p.thesis ? ` thesis="${p.thesis.replace(/\s+/g, " ").slice(0, 80)}"` : ""}`
    );
  }
  const pads = launchpadRotation(snap);
  if (pads.length) {
    lines.push("By launchpad (open size, size-weighted 24h, unrealized, realized, wins/closes):");
    for (const r of pads.slice(0, 8)) {
      lines.push(
        `- ${r.label}: ${n(r.sizeUsd)} 24h=${r.move24hPct == null ? "n/a" : r.move24hPct.toFixed(1) + "%"} u=${n(r.unrealizedUsd)} r=${n(r.realizedUsd)} ${r.wins}/${r.closes}`
      );
    }
  }
  const stories = narrativeRotation(snap);
  if (stories.length) {
    lines.push(
      `By narrative: ${stories.slice(0, 8).map((r) => `${r.label} ${n(r.sizeUsd)} net=${n(r.totalPnlUsd)}`).join(" | ")}`
    );
  }
  if (snap.closedTrades.length) {
    lines.push("Recent closes:");
    for (const t of snap.closedTrades.slice(0, 6)) {
      lines.push(`- ${t.symbol} ${n(t.realizedPnl)} ${t.exitDate.slice(0, 10)}`);
    }
  }
  if (snap.alerts.length) {
    lines.push(`Alerts: ${snap.alerts.map((a) => a.message).join(" | ")}`);
  }
  lines.push(
    "Desk rules: cash floor 20%, single-name cap ~15% once book is large, size down after 8% drawdown, do not invent fills FOMO did not capture."
  );
  return lines.join("\n");
}
function n(v) {
  return v.toFixed(2);
}
function pct(part, whole) {
  if (!whole) return "0%";
  return `${(part / whole * 100).toFixed(0)}%`;
}

// src/lib/ai/runChat.ts
var SYSTEM = `You are the FOMO desk copilot on rxlfomo. You see a live portfolio snapshot (wallet + FOMO + Dex 24h + Relay).
Answer like a trading desk: short, specific, numbered when useful.
Never invent closed-trade PnL, entries, or fills that are not in the snapshot. If cost basis is missing, say the number is 24h mark-to-market, not all-time PnL.
Cash = SOL + stables. Flag names >15% of equity and cash <20%.
Each name carries its launchpad (Pons, Bankr, Pump.fun, Stonk.fun\u2026) and narrative tags; "Stonks" means paired against a tokenized stock. For rotation questions, compare launchpads/narratives by size-weighted 24h move and realized vs unrealized, and say which bucket is heating up or bleeding.
If the operator asks what to do, give a risk action (trim / hold / wait for cash) rather than a new meme call unless they ask for one.`;
var ChatConfigError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "ChatConfigError";
  }
};
function resolveLlmConfig(env, headerKey) {
  const apiKey = headerKey || env.LLM_API_KEY || env.AI_GATEWAY_API_KEY || env.OPENAI_API_KEY || "";
  const baseUrl = env.LLM_BASE_URL || env.OPENAI_BASE_URL || env.AI_GATEWAY_BASE_URL || "";
  const model = env.LLM_MODEL || "gpt-5.4";
  return { apiKey, baseUrl, model };
}
async function runPortfolioChat(input) {
  if (!input.apiKey.trim()) {
    throw new ChatConfigError(
      "Attach an LLM key: set LLM_API_KEY (OpenAI-compatible) or AI_GATEWAY_API_KEY on the server, or paste it in Sources."
    );
  }
  const modelId = (input.model || "gpt-5.4").trim();
  const openai = createOpenAI({
    apiKey: input.apiKey.trim(),
    ...input.baseUrl ? { baseURL: input.baseUrl.replace(/\/$/, "") } : {}
  });
  const book = input.snapshot ? compactBook(input.snapshot) : "No live book is loaded.";
  const history = input.messages.filter((m) => (m.role === "user" || m.role === "assistant") && m.content.trim()).slice(-12).map((m) => `${m.role === "user" ? "Operator" : "Desk"}: ${m.content.trim()}`).join("\n");
  const { text } = await generateText({
    model: openai(modelId.replace(/^openai\//, "")),
    system: SYSTEM,
    prompt: `LIVE BOOK
${book}

THREAD
${history || "(none yet)"}

Reply as Desk.`,
    abortSignal: AbortSignal.timeout(55e3)
  });
  return { text: text.trim(), model: modelId };
}

// server/vercel-chat.ts
var config = {
  maxDuration: 60
};
function first(value) {
  if (Array.isArray(value)) return value[0] || "";
  return value || "";
}
function headerValue(headers, name) {
  if (headers && typeof headers.get === "function") {
    return headers.get(name) || "";
  }
  const rec = headers;
  return first(rec[name] || rec[name.toLowerCase()]);
}
async function readBody(req) {
  const raw = req.body;
  if (typeof raw === "string") {
    try {
      return raw ? JSON.parse(raw) : {};
    } catch {
      return {};
    }
  }
  if (raw && typeof raw === "object" && !Buffer.isBuffer(raw)) {
    return raw;
  }
  if (Buffer.isBuffer(raw)) {
    try {
      return JSON.parse(raw.toString("utf8"));
    } catch {
      return {};
    }
  }
  return {};
}
function json(res, status, body) {
  res.setHeader?.("content-type", "application/json; charset=utf-8");
  res.setHeader?.("cache-control", "no-store");
  res.status(status).json(body);
}
async function handler(req, res) {
  try {
    if (req.method === "OPTIONS") {
      res.status(204).end();
      return;
    }
    if (req.method && req.method !== "POST") {
      json(res, 405, { error: "method", message: "POST /api/chat" });
      return;
    }
    const body = await readBody(req);
    const hasUser = (body.messages || []).some((m) => m.role === "user" && m.content?.trim());
    if (!hasUser) {
      json(res, 400, { error: "config", message: "Send a user message" });
      return;
    }
    const llm = resolveLlmConfig(process.env, headerValue(req.headers, "x-llm-api-key"));
    const result = await runPortfolioChat({
      messages: body.messages || [],
      snapshot: body.snapshot,
      apiKey: llm.apiKey,
      baseUrl: body.baseUrl || llm.baseUrl || void 0,
      model: body.model || llm.model
    });
    json(res, 200, result);
  } catch (err) {
    const status = err instanceof ChatConfigError ? 400 : 502;
    json(res, status, {
      error: err instanceof ChatConfigError ? "config" : "upstream",
      message: err instanceof Error ? err.message : "Chat failed"
    });
  }
}
export {
  config,
  handler as default
};
