/* generated by scripts/bundle-api.mjs — do not edit */

// src/lib/launchpad/classify.ts
function isStockTicker(symbol) {
  const s = symbol.trim();
  return STOCK_TICKERS.has(s.toUpperCase()) || STOCK_TICKERS.has(s.replace(/[a-z]+$/, "").toUpperCase());
}
var STOCK_TICKERS = /* @__PURE__ */ new Set([
  "SPY",
  "QQQ",
  "META",
  "TSLA",
  "NVDA",
  "AAPL",
  "AMZN",
  "GOOGL",
  "GOOG",
  "MSFT",
  "HOOD",
  "AMC",
  "GME",
  "COIN",
  "MSTR",
  "SGOV",
  "PLTR",
  "NFLX",
  "AMD",
  "INTC",
  "BABA",
  "DIS",
  "UBER",
  "CRCL",
  "IWM",
  "DIA",
  "TLT",
  "GLD",
  "SLV",
  "ARKK",
  "SOFI",
  "RDDT",
  "SMCI",
  "AVGO",
  "ORCL"
]);
var NARRATIVES = [
  {
    tag: "Stonks",
    test: ({ symbol, name, quote }) => quote !== "" && isStockTicker(quote) || /stonk|stock/i.test(`${symbol} ${name} ${quote}`)
  },
  { tag: "NEAR", test: ({ symbol, name, quote }) => /near/i.test(`${symbol} ${name} ${quote}`) },
  {
    tag: "Privacy",
    test: ({ symbol, name, quote }) => /\b(w?zec|w?xmr)\b|zcash|monero|privacy/i.test(`${symbol} ${name} ${quote}`)
  },
  { tag: "Muse", test: ({ symbol, name, quote }) => /muse/i.test(`${symbol} ${name} ${quote}`) },
  {
    tag: "AI / agents",
    test: ({ symbol, name }) => /\b(ai|gpt|agents?|llm)\b|bot|402/i.test(`${symbol} ${name}`)
  },
  {
    tag: "RWA / tokenization",
    test: ({ symbol, name }) => /tokeniz|rwa|debt|treasur|bond|yield/i.test(`${symbol} ${name}`)
  },
  {
    tag: "Animals",
    test: ({ symbol, name, quote }) => /dog|doge|cat|bear|frog|pepe|\bape\b|monkey|bull|penguin|inu|shib|wif|bonk|kat\b/i.test(
      `${symbol} ${name} ${quote}`
    )
  },
  {
    tag: "CT figures",
    test: ({ symbol, name }) => /ansem|vlad|tenev|elon|trump|saylor|cz\b/i.test(`${symbol} ${name}`)
  }
];
function narrativesFor(input) {
  const t = { symbol: input.symbol || "", name: input.name || "", quote: input.quote || "" };
  const tags = NARRATIVES.filter((n) => n.test(t)).map((n) => n.tag);
  return tags.length ? tags : ["Other"];
}

// src/lib/scanner/rules.ts
var RULES = { maxNamePct: 15, minCashPct: 20, drawdownCutPct: -8, maxTop3Pct: 45 };
var SCAN_CHAINS = /* @__PURE__ */ new Set(["solana", "base", "bsc"]);
var MAX_RUNNER_AGE_HOURS = 48;
var MIN_RUNNER_SCORE = 30;
var DROP_SYMBOLS = /* @__PURE__ */ new Set(["SOL", "WSOL", "USDC", "USDT", "ETH", "WETH", "BNB", "WBNB"]);
var SMALL_BOOK = { minLiq: 3e3, sizeFloorLiq: 8e3 };
var LARGE_BOOK = { minLiq: 15e3, sizeFloorLiq: 4e4 };
var ACCOUNT_FLOORS = {
  busymeredog: SMALL_BOOK,
  softmereelk: LARGE_BOOK
};
function floorsFor(handle, equity) {
  const known = ACCOUNT_FLOORS[handle.replace(/^@/, "").trim().toLowerCase()];
  if (known) return known;
  return equity >= 5e4 ? LARGE_BOOK : SMALL_BOOK;
}
function droppedSymbol(symbol) {
  return DROP_SYMBOLS.has(symbol.trim().toUpperCase());
}
function scannerLaunchpad(dexId, mint) {
  const d = dexId.trim().toLowerCase();
  if (d === "pump-fun" || d === "pumpfun" || d === "pumpswap" || !mint.startsWith("0x") && mint.toLowerCase().endsWith("pump")) {
    return "Pump.fun";
  }
  if (d.startsWith("stonkfun")) return "Stonk.fun";
  if (d.startsWith("pons")) return "Pons";
  if (d.startsWith("bankr")) return "Bankr";
  if (/^(raydium|meteora|orca)/.test(d)) return "Direct / DEX";
  return void 0;
}
function mintKey(mint) {
  return mint.startsWith("0x") ? mint.toLowerCase() : mint;
}
function runnerScore(input) {
  const age = input.ageHours;
  const fresh = age == null ? 0 : age < 2 ? 30 : age < 6 ? 22 : age < 24 ? 12 : age < 48 ? 4 : 0;
  const chg = input.change1hPct;
  const early = chg == null || chg < 0 ? 0 : chg >= 8 && chg <= 45 ? 20 : chg > 80 ? 4 : 10;
  const buys = input.buys1h ?? 0;
  const txns = buys + (input.sells1h ?? 0);
  const share = txns > 0 ? buys / txns : null;
  const buyers = share == null ? 0 : share >= 0.58 && txns >= 40 ? 20 : share < 0.45 ? 0 : 10;
  const liq = input.liquidityUsd;
  const exit = liq >= input.floors.sizeFloorLiq ? 20 : liq < input.floors.minLiq ? 0 : 10;
  const turnover = liq > 0 ? input.volume1hUsd / liq : Infinity;
  const wash = turnover < 8 ? 10 : turnover > 20 ? 0 : 5;
  return fresh + early + buyers + exit + wash;
}
function isExtended(row) {
  const turnover = row.liquidityUsd > 0 ? row.volume1hUsd / row.liquidityUsd : Infinity;
  return turnover > 8 || (row.change1hPct ?? 0) > 80;
}
function runnerLabel(score) {
  if (score >= 75) return "early";
  if (score >= 50) return "building";
  if (score >= MIN_RUNNER_SCORE) return "chase";
  return null;
}
var SOURCE_LABEL = {
  "dex-boost": "Dex boost",
  "dex-profile": "Dex profile",
  "gecko-new": "Gecko new pool",
  "gecko-trending": "Gecko trending 1h"
};
function usd(v) {
  const a = Math.abs(v);
  if (a >= 1e6) return `$${(a / 1e6).toFixed(1)}M`;
  if (a >= 1e3) return `$${(a / 1e3).toFixed(a >= 1e4 ? 0 : 1)}k`;
  return `$${a.toFixed(0)}`;
}
function ageText(h) {
  if (h < 1) return `${Math.max(1, Math.round(h * 60))}m`;
  if (h < 48) return `${h.toFixed(0)}h`;
  return `${Math.round(h / 24)}d`;
}
function dedupe(plays) {
  const seenMint = /* @__PURE__ */ new Set();
  const seenSymbol = /* @__PURE__ */ new Set();
  const out = [];
  for (const p of plays) {
    const m = `${p.chain}:${mintKey(p.mint)}`;
    const sym = p.symbol.trim().toUpperCase();
    if (seenMint.has(m) || seenSymbol.has(sym)) continue;
    seenMint.add(m);
    seenSymbol.add(sym);
    out.push(p);
  }
  return out;
}
var MAX_BOARD = 12;
function buildRunners(input) {
  const floors = floorsFor(input.handle, 0);
  const plays = [];
  for (const row of input.tape) {
    if (!SCAN_CHAINS.has(row.chain) || droppedSymbol(row.symbol)) continue;
    if (row.liquidityUsd < floors.minLiq) continue;
    if (row.ageHours == null || row.ageHours > MAX_RUNNER_AGE_HOURS) continue;
    const rawScore = runnerScore({ ...row, floors });
    const extended = isExtended(row);
    const score = extended ? Math.min(rawScore, 49) : rawScore;
    const label = extended && score >= MIN_RUNNER_SCORE ? "chase" : runnerLabel(score);
    if (!label) continue;
    const launchpad = scannerLaunchpad(row.dexId, row.mint);
    const themes = narrativesFor({ symbol: row.symbol, name: row.name, quote: row.quoteSymbol }).filter(
      (t) => t !== "Other"
    );
    const buys = row.buys1h ?? 0;
    const txns = buys + (row.sells1h ?? 0);
    const chg = row.change1hPct;
    plays.push({
      account: input.handle,
      mint: row.mint,
      symbol: row.symbol,
      chain: row.chain,
      launchpad: launchpad || "Unknown",
      themes,
      trigger: row.sources.map((x) => SOURCE_LABEL[x]).join(" + ") || "tape",
      bookEdge: "New to this book",
      bookFit: "new",
      sizeCapUsd: 0,
      vetoes: [],
      decision: "watch",
      lastCall: `WATCH_${label.toUpperCase()}`,
      reason: `Launched ${ageText(row.ageHours)} ago, ${chg == null ? "1h n/a" : `${chg >= 0 ? "+" : ""}${chg.toFixed(0)}% in 1h`}, ${txns ? `${Math.round(buys / txns * 100)}% buys over ${txns} txns` : "no 1h txns"}, ${usd(row.liquidityUsd)} liquidity.`,
      score,
      runnerScore: score,
      runnerLabel: label,
      liquidityUsd: row.liquidityUsd,
      volume1hUsd: row.volume1hUsd,
      marketCapUsd: row.marketCapUsd,
      fdvUsd: row.fdvUsd,
      launchedAt: row.launchedAt,
      change5mPct: row.change5mPct,
      change1hPct: row.change1hPct,
      change6hPct: row.change6hPct,
      buys1h: row.buys1h,
      sells1h: row.sells1h,
      ageHours: row.ageHours,
      pairUrl: row.pairUrl,
      website: row.website,
      twitter: row.twitter,
      telegram: row.telegram,
      sources: row.sources,
      arrived: input.previous ? !input.previous.has(mintKey(row.mint)) : false
    });
  }
  plays.sort((a, b) => b.runnerScore - a.runnerScore || b.liquidityUsd - a.liquidityUsd);
  const trending = (p) => p.sources.includes("gecko-trending") ? 1 : 0;
  return dedupe(plays).sort(
    (a, b) => (a.ageHours ?? Infinity) - (b.ageHours ?? Infinity) || b.runnerScore - a.runnerScore || trending(b) - trending(a)
  ).slice(0, input.limit ?? MAX_BOARD);
}

// src/lib/scanner/tape.ts
var DEX = "https://api.dexscreener.com";
var GECKO = "https://api.geckoterminal.com/api/v2";
var TAPE_TTL_MS = 12e3;
var PAIR_TTL_MS = 12e3;
var PAIR_BATCH = 30;
var PAIR_KEEP_MS = 10 * 6e4;
var cache = null;
var inflight = null;
var pairs = /* @__PURE__ */ new Map();
async function getJson(url, fetchFn, timeoutMs = 8e3) {
  const res = await fetchFn(url, {
    headers: { accept: "application/json" },
    signal: AbortSignal.timeout(timeoutMs)
  });
  if (!res.ok) throw new Error(`${new URL(url).host} ${res.status}`);
  return await res.json();
}
function key(chain, mint) {
  return `${chain}:${mint.startsWith("0x") ? mint.toLowerCase() : mint}`;
}
function num(v) {
  const n = typeof v === "string" ? Number(v) : typeof v === "number" ? v : NaN;
  return Number.isFinite(n) ? n : 0;
}
function numOrNull(v) {
  if (v == null || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}
function positiveOrNull(v) {
  const n = numOrNull(v);
  return n != null && n > 0 ? n : null;
}
function social(pair, type) {
  return pair.info?.socials?.find((x) => x.type?.toLowerCase() === type && x.url)?.url;
}
function rowFromDexPair(pair, sources, now = Date.now()) {
  const mint = pair.baseToken?.address;
  const chain = pair.chainId || "";
  if (!mint || !SCAN_CHAINS.has(chain)) return null;
  return {
    chain,
    mint,
    symbol: pair.baseToken?.symbol || "?",
    name: pair.baseToken?.name || "",
    dexId: pair.dexId || "",
    quoteSymbol: pair.quoteToken?.symbol || "",
    liquidityUsd: num(pair.liquidity?.usd),
    volume1hUsd: num(pair.volume?.h1),
    marketCapUsd: positiveOrNull(pair.marketCap),
    fdvUsd: positiveOrNull(pair.fdv),
    launchedAt: pair.pairCreatedAt ? new Date(pair.pairCreatedAt).toISOString() : null,
    change5mPct: numOrNull(pair.priceChange?.m5),
    change1hPct: numOrNull(pair.priceChange?.h1),
    change6hPct: numOrNull(pair.priceChange?.h6),
    buys1h: numOrNull(pair.txns?.h1?.buys),
    sells1h: numOrNull(pair.txns?.h1?.sells),
    ageHours: pair.pairCreatedAt ? Math.max(0, (now - pair.pairCreatedAt) / 36e5) : null,
    pairUrl: pair.url || `https://dexscreener.com/${chain}/${mint}`,
    website: pair.info?.websites?.find((w) => w.url)?.url,
    twitter: social(pair, "twitter"),
    telegram: social(pair, "telegram"),
    sources: [...sources]
  };
}
function rowFromGeckoPool(pool, source, now = Date.now()) {
  const a = pool.attributes;
  const baseId = pool.relationships?.base_token?.data?.id || "";
  if (!a || !baseId.startsWith("solana_")) return null;
  const [base = "?", quote = ""] = (a.name || "").split(" / ");
  const created = a.pool_created_at ? Date.parse(a.pool_created_at) : NaN;
  return {
    chain: "solana",
    mint: baseId.slice("solana_".length),
    symbol: base.trim(),
    name: base.trim(),
    dexId: pool.relationships?.dex?.data?.id || "",
    quoteSymbol: quote.trim(),
    liquidityUsd: num(a.reserve_in_usd),
    volume1hUsd: num(a.volume_usd?.h1),
    marketCapUsd: positiveOrNull(a.market_cap_usd),
    fdvUsd: positiveOrNull(a.fdv_usd),
    launchedAt: Number.isFinite(created) ? new Date(created).toISOString() : null,
    change5mPct: numOrNull(a.price_change_percentage?.m5),
    change1hPct: numOrNull(a.price_change_percentage?.h1),
    change6hPct: numOrNull(a.price_change_percentage?.h6),
    buys1h: numOrNull(a.transactions?.h1?.buys),
    sells1h: numOrNull(a.transactions?.h1?.sells),
    ageHours: Number.isFinite(created) ? Math.max(0, (now - created) / 36e5) : null,
    pairUrl: `https://www.geckoterminal.com/solana/pools/${a.address || ""}`,
    sources: [source]
  };
}
function bestPairs(list) {
  const out = /* @__PURE__ */ new Map();
  for (const p of list) {
    const mint = p.baseToken?.address;
    if (!mint || !p.chainId) continue;
    const k = key(p.chainId, mint);
    const prev = out.get(k);
    if (!prev || num(p.liquidity?.usd) > num(prev.liquidity?.usd)) out.set(k, p);
  }
  return out;
}
function pickPairBatch(keys, filled, now, cap = PAIR_BATCH) {
  const fresh = keys.filter((k) => !filled.has(k));
  const stale = keys.filter((k) => filled.has(k) && now - filled.get(k).at >= PAIR_TTL_MS).sort((a, b) => filled.get(a).at - filled.get(b).at);
  return [.../* @__PURE__ */ new Set([...fresh, ...stale])].slice(0, cap);
}
async function loadTape(fetchFn, now) {
  const warnings = [];
  const settle = async (label, p, empty) => {
    try {
      return await p;
    } catch (err) {
      warnings.push(`${label}: ${err instanceof Error ? err.message : "failed"}`);
      return empty;
    }
  };
  const [boosts, profiles, fresh, trending] = await Promise.all([
    settle("Dex boosts", getJson(`${DEX}/token-boosts/latest/v1`, fetchFn), []),
    settle("Dex profiles", getJson(`${DEX}/token-profiles/latest/v1`, fetchFn), []),
    settle(
      "Gecko new pools",
      getJson(`${GECKO}/networks/solana/new_pools?page=1`, fetchFn),
      { data: [] }
    ),
    settle(
      "Gecko trending",
      getJson(`${GECKO}/networks/solana/trending_pools?duration=1h`, fetchFn),
      { data: [] }
    )
  ]);
  const listed = /* @__PURE__ */ new Map();
  const add = (chain, mint, source) => {
    if (!SCAN_CHAINS.has(chain)) return;
    const k = key(chain, mint);
    const row = listed.get(k) || { chain, mint, sources: [] };
    if (!row.sources.includes(source)) row.sources.push(source);
    listed.set(k, row);
  };
  for (const it of Array.isArray(boosts) ? boosts : []) {
    if (it.chainId && it.tokenAddress) add(it.chainId, it.tokenAddress, "dex-boost");
  }
  for (const it of Array.isArray(profiles) ? profiles : []) {
    if (it.chainId && it.tokenAddress) add(it.chainId, it.tokenAddress, "dex-profile");
  }
  const geckoRows = /* @__PURE__ */ new Map();
  for (const pool of fresh.data || []) {
    const row = rowFromGeckoPool(pool, "gecko-new", now);
    if (!row) continue;
    const k = key(row.chain, row.mint);
    if (!geckoRows.has(k)) geckoRows.set(k, row);
    add(row.chain, row.mint, "gecko-new");
  }
  const trendingKeys = /* @__PURE__ */ new Set();
  for (const pool of trending.data || []) {
    const row = rowFromGeckoPool(pool, "gecko-trending", now);
    if (row) trendingKeys.add(key(row.chain, row.mint));
  }
  const batch = pickPairBatch([...listed.keys()], pairs, now);
  const byChain = /* @__PURE__ */ new Map();
  for (const k of batch) {
    const it = listed.get(k);
    byChain.set(it.chain, [...byChain.get(it.chain) || [], it.mint]);
  }
  const fetched = await Promise.all(
    [...byChain.entries()].map(
      ([chain, mints]) => settle(`Dex pairs ${chain}`, getJson(`${DEX}/tokens/v1/${chain}/${mints.join(",")}`, fetchFn), [])
    )
  );
  for (const [k, pair] of bestPairs(fetched.flat().filter(Boolean))) pairs.set(k, { at: now, pair });
  for (const [k, v] of pairs) if (now - v.at > PAIR_KEEP_MS) pairs.delete(k);
  const rows = [];
  for (const [k, it] of listed) {
    const sources = trendingKeys.has(k) ? [...it.sources, "gecko-trending"] : it.sources;
    const pair = pairs.get(k)?.pair;
    const fallback = geckoRows.get(k);
    const row = pair ? rowFromDexPair(pair, sources, now) : fallback ? { ...fallback, sources } : null;
    if (row && !droppedSymbol(row.symbol)) rows.push(row);
  }
  return { rows, warnings, fetchedAt: now };
}
async function fetchTape(fetchFn = fetch, now = Date.now()) {
  if (cache && now - cache.fetchedAt < TAPE_TTL_MS) return cache;
  if (!inflight) {
    inflight = loadTape(fetchFn, now).then((result) => {
      if (result.rows.length) cache = result;
      return result;
    }).finally(() => {
      inflight = null;
    });
  }
  return inflight;
}

// server/vercel-plays.ts
var config = {
  maxDuration: 30
};
var lastBoard = /* @__PURE__ */ new Map();
function first(value) {
  if (Array.isArray(value)) return value[0] || "";
  return value || "";
}
function queryValue(req, name) {
  if (req.query) return first(req.query[name]);
  try {
    return new URL(req.url || "", "http://localhost").searchParams.get(name) || "";
  } catch {
    return "";
  }
}
function json(res, status, body) {
  res.setHeader?.("content-type", "application/json; charset=utf-8");
  res.setHeader?.("cache-control", "no-store");
  res.status(status).json(body);
}
async function handler(req, res, env = process.env) {
  try {
    if (req.method === "OPTIONS") {
      res.status(204).end();
      return;
    }
    if (req.method && req.method !== "GET") {
      json(res, 405, { error: "method", message: "GET /api/plays?handle=" });
      return;
    }
    const defaultHandle = env.FOMO_HANDLE || env.VITE_FOMO_HANDLE || "";
    const handle = (queryValue(req, "handle") || defaultHandle).replace(/^@/, "").trim();
    if (!handle) {
      json(res, 400, { error: "config", message: "GET /api/plays?handle=<fomo handle>" });
      return;
    }
    const k = handle.toLowerCase();
    const tape = await fetchTape();
    const plays = buildRunners({ handle, tape: tape.rows, previous: lastBoard.get(k) });
    lastBoard.set(k, new Set(plays.map((p) => p.mint.startsWith("0x") ? p.mint.toLowerCase() : p.mint)));
    const body = {
      generatedAt: new Date(tape.fetchedAt).toISOString(),
      tapeCount: tape.rows.length,
      rules: RULES,
      books: [],
      plays
    };
    json(res, 200, body);
  } catch (err) {
    json(res, 502, {
      error: "upstream",
      message: err instanceof Error ? err.message : "Failed to read plays"
    });
  }
}
export {
  config,
  handler as default
};
