/* generated by scripts/bundle-api.mjs from server/vercel-portfolio.ts — do not edit */

// src/lib/fomo/client.ts
var DEFAULT_BASE = "https://api.fomoapi.io";
var FomoApiError = class extends Error {
  status;
  code;
  body;
  constructor(status, message, body) {
    super(message);
    this.status = status;
    this.body = body;
    if (status === 401) this.code = "auth";
    else if (status === 402) this.code = "credits";
    else if (status === 404) this.code = "not_found";
    else this.code = "upstream";
  }
};
function headers(apiKey) {
  return {
    authorization: `Bearer ${apiKey}`,
    accept: "application/json"
  };
}
async function getJson(fetchFn, url, apiKey, timeoutMs = 45e3) {
  const res = await fetchFn(url, {
    headers: headers(apiKey),
    signal: AbortSignal.timeout(timeoutMs)
  });
  const text = await res.text();
  let body = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = { raw: text.slice(0, 400) };
  }
  if (!res.ok) {
    const errObj = body;
    throw new FomoApiError(
      res.status,
      errObj?.message || errObj?.error || `FOMO API ${res.status}`,
      body
    );
  }
  return body;
}
function createFomoClient(opts) {
  const base = (opts.baseUrl || DEFAULT_BASE).replace(/\/$/, "");
  const fetchFn = opts.fetchFn ?? fetch;
  const key = opts.apiKey;
  return {
    resolveUser(handle) {
      const h = encodeURIComponent(handle.replace(/^@/, ""));
      return getJson(fetchFn, `${base}/v2/users/${h}`, key, 9e4);
    },
    search(query) {
      const q = encodeURIComponent(query.replace(/^@/, ""));
      return getJson(
        fetchFn,
        `${base}/v2/search?q=${q}&type=traders&limit=5`,
        key,
        2e4
      );
    },
    positions(handle, query = "deep=1&limit=500") {
      const h = encodeURIComponent(handle.replace(/^@/, ""));
      return getJson(
        fetchFn,
        `${base}/v2/users/${h}/positions?${query}`,
        key,
        45e3
      );
    },
    balances(handle) {
      const h = encodeURIComponent(handle.replace(/^@/, ""));
      return getJson(
        fetchFn,
        `${base}/v2/users/${h}/balances`,
        key,
        45e3
      );
    },
    leaderboard(window = "all", limit = 150) {
      return getJson(
        fetchFn,
        `${base}/v2/leaderboard/${window}?limit=${limit}`,
        key,
        3e4
      );
    }
  };
}

// src/lib/wallet/markets.ts
var DEX_TOKENS = "https://api.dexscreener.com/latest/dex/tokens";
function pickBestPair(pairs, mint) {
  const lower = mint.toLowerCase();
  const relevant = pairs.filter((p) => p.baseToken?.address?.toLowerCase() === lower);
  return [...relevant].sort(
    (a, b) => (b.liquidity?.usd ?? 0) - (a.liquidity?.usd ?? 0)
  )[0];
}
async function fetchDexMarkets(mints, fetchFn = fetch) {
  const out = /* @__PURE__ */ new Map();
  const unique = [...new Set(mints.filter(Boolean))];
  const chunkSize = 25;
  for (let i = 0; i < unique.length; i += chunkSize) {
    const chunk = unique.slice(i, i + chunkSize);
    const url = `${DEX_TOKENS}/${chunk.join(",")}`;
    try {
      const res = await fetchFn(url, { signal: AbortSignal.timeout(15e3) });
      if (!res.ok) continue;
      const body = await res.json();
      const pairs = Array.isArray(body) ? body : body.pairs ?? [];
      for (const mint of chunk) {
        const best = pickBestPair(pairs, mint);
        if (!best?.priceUsd) continue;
        const priceUsd = Number(best.priceUsd);
        if (!Number.isFinite(priceUsd)) continue;
        const isBase = best.baseToken?.address?.toLowerCase() === mint.toLowerCase();
        out.set(mint, {
          priceUsd,
          marketCapUsd: Number(best.marketCap || best.fdv || 0) || 0,
          liquidityUsd: Number(best.liquidity?.usd || 0) || 0,
          symbol: isBase ? best.baseToken?.symbol : best.quoteToken?.symbol,
          name: isBase ? best.baseToken?.name : best.quoteToken?.name
        });
      }
    } catch {
    }
  }
  return out;
}
async function fetchSolPriceUsd(fetchFn = fetch) {
  try {
    const res = await fetchFn(
      "https://api.geckoterminal.com/api/v2/simple/networks/solana/token_price/So11111111111111111111111111111111111111112",
      { signal: AbortSignal.timeout(1e4) }
    );
    if (!res.ok) return 0;
    const body = await res.json();
    const raw = body.data?.attributes?.token_prices?.["So11111111111111111111111111111111111111112"];
    const n = Number(raw);
    return Number.isFinite(n) ? n : 0;
  } catch {
    return 0;
  }
}

// src/lib/wallet/solana.ts
var TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
var TOKEN_2022_PROGRAM = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
var WSOL = "So11111111111111111111111111111111111111112";
var RPC_CANDIDATES = [
  "https://api.mainnet-beta.solana.com",
  "https://solana-rpc.publicnode.com"
];
async function rpc(url, method, params, fetchFn) {
  const res = await fetchFn(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
    signal: AbortSignal.timeout(2e4)
  });
  const text = await res.text();
  let body;
  try {
    body = text ? JSON.parse(text) : {};
  } catch {
    throw new Error(`Solana RPC HTTP ${res.status}`);
  }
  if (!res.ok) throw new Error(body.error?.message || `Solana RPC HTTP ${res.status}`);
  if (body.error) throw new Error(body.error.message || "Solana RPC error");
  return body.result;
}
async function rpcWithFallback(urls, method, params, fetchFn) {
  let last = new Error("No Solana RPC endpoints");
  for (const url of urls) {
    try {
      return await rpc(url, method, params, fetchFn);
    } catch (err) {
      last = err instanceof Error ? err : new Error(String(err));
    }
  }
  throw last;
}
function rpcList(preferred) {
  const urls = preferred ? [preferred, ...RPC_CANDIDATES] : [...RPC_CANDIDATES];
  return [...new Set(urls)];
}
async function tokenAccounts(rpcUrls, owner, programId, fetchFn) {
  const result = await rpcWithFallback(
    rpcUrls,
    "getTokenAccountsByOwner",
    [owner, { programId }, { encoding: "jsonParsed" }],
    fetchFn
  );
  return (result.value ?? []).map((row) => {
    const info = row.account.data.parsed.info;
    return {
      mint: info.mint,
      amount: Number(info.tokenAmount.uiAmount ?? 0),
      decimals: info.tokenAmount.decimals,
      chain: "solana"
    };
  }).filter((h) => h.amount > 0);
}
function collapseByMint(rows) {
  const map = /* @__PURE__ */ new Map();
  for (const h of rows) {
    const prev = map.get(h.mint);
    if (!prev) {
      map.set(h.mint, { ...h });
      continue;
    }
    prev.amount += h.amount;
    prev.native = Boolean(prev.native || h.native);
    if (h.valueUsd != null || prev.valueUsd != null) {
      prev.valueUsd = (prev.valueUsd ?? 0) + (h.valueUsd ?? 0);
    }
    prev.symbol = prev.native ? "SOL" : prev.symbol || h.symbol;
  }
  return [...map.values()];
}
async function fetchSolanaHoldings(opts) {
  const fetchFn = opts.fetchFn ?? fetch;
  if (opts.heliusApiKey) {
    try {
      return await fetchHeliusHoldings(opts.owner, opts.heliusApiKey, fetchFn);
    } catch {
    }
  }
  const rpcUrls = rpcList(opts.rpcUrl);
  const [lamports, spl, t22] = await Promise.all([
    rpcWithFallback(rpcUrls, "getBalance", [opts.owner], fetchFn),
    tokenAccounts(rpcUrls, opts.owner, TOKEN_PROGRAM, fetchFn),
    tokenAccounts(rpcUrls, opts.owner, TOKEN_2022_PROGRAM, fetchFn).catch(
      () => []
    )
  ]);
  const native = {
    mint: WSOL,
    amount: lamports.value / 1e9,
    decimals: 9,
    symbol: "SOL",
    name: "Solana",
    chain: "solana",
    native: true
  };
  const wrappedSol = [...spl, ...t22].filter((h) => h.mint === WSOL).reduce((s, h) => s + h.amount, 0);
  native.amount += wrappedSol;
  const tokens = collapseByMint([...spl, ...t22].filter((h) => h.mint !== WSOL));
  return collapseByMint(native.amount > 0 ? [native, ...tokens] : tokens);
}
async function fetchHeliusHoldings(owner, apiKey, fetchFn) {
  const url = `https://mainnet.helius-rpc.com/?api-key=${apiKey}`;
  const res = await fetchFn(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 1,
      method: "getAssetsByOwner",
      params: {
        ownerAddress: owner,
        page: 1,
        limit: 1e3,
        displayOptions: { showFungible: true, showNativeBalance: true }
      }
    }),
    signal: AbortSignal.timeout(2e4)
  });
  const body = await res.json();
  if (body.error) throw new Error(body.error.message || "Helius error");
  const data = body.result ?? {};
  const out = [];
  const lamports = data.nativeBalance?.lamports ?? 0;
  if (lamports > 0) {
    out.push({
      mint: WSOL,
      amount: lamports / 1e9,
      decimals: 9,
      symbol: "SOL",
      name: "Solana",
      priceUsd: data.nativeBalance?.price_per_sol,
      valueUsd: data.nativeBalance?.price_per_sol != null ? lamports / 1e9 * data.nativeBalance.price_per_sol : void 0,
      chain: "solana",
      native: true
    });
  }
  for (const item of data.items ?? []) {
    const info = item.token_info;
    if (!info || !item.id) continue;
    const decimals = info.decimals ?? 0;
    const raw = Number(info.balance ?? 0);
    const amount = decimals >= 0 ? raw / 10 ** decimals : raw;
    if (amount <= 0) continue;
    const price = info.price_info?.price_per_token;
    out.push({
      mint: item.id,
      amount,
      decimals,
      symbol: info.symbol || item.content?.metadata?.symbol,
      name: item.content?.metadata?.name,
      priceUsd: price,
      valueUsd: info.price_info?.total_price ?? (price != null ? amount * price : void 0),
      chain: "solana"
    });
  }
  return collapseByMint(out);
}

// src/lib/portfolio/helpers.ts
var STABLE_SYMBOLS = /* @__PURE__ */ new Set([
  "USDC",
  "USDT",
  "USD1",
  "PYUSD",
  "USDS",
  "DAI",
  "FDUSD",
  "CASH",
  "USD",
  "USDC.E"
]);
var STABLE_MINTS = /* @__PURE__ */ new Set([
  "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  // USDC
  "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
  // USDT
  "USD1ttGY1N17NEEHLmELoaybftRBUSErhqYiQzvEmuB",
  "2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo"
  // PYUSD
]);
var WSOL2 = "So11111111111111111111111111111111111111112";
function isCashAsset(symbol, mint) {
  const sym = (symbol || "").toUpperCase();
  if (sym === "SOL" || sym === "WSOL") return true;
  if (STABLE_SYMBOLS.has(sym)) return true;
  if (mint && (mint === WSOL2 || STABLE_MINTS.has(mint))) return true;
  return false;
}
function normalizeChain(raw, networkId) {
  const s = (raw || "").toLowerCase();
  if (networkId === 1399811149 || s.includes("sol")) return "solana";
  if (networkId === 8453 || s.includes("base")) return "base";
  if (networkId === 56 || s.includes("bnb") || s.includes("bsc")) return "bnb";
  if (networkId === 1 || s === "eth" || s.includes("ethereum")) return "ethereum";
  if (networkId === 4663 || s.includes("robin") || s.includes("hood")) return "robinhood";
  if (networkId === 143 || s.includes("monad")) return "monad";
  if (s.includes("hyper")) return "hyperliquid";
  return "other";
}
function hoursBetween(from, to) {
  if (!from) return 0;
  const a = Date.parse(from);
  const b = to ? Date.parse(to) : Date.now();
  if (!Number.isFinite(a) || !Number.isFinite(b)) return 0;
  return Math.max(0, (b - a) / 36e5);
}
function asNumber(value, fallback = 0) {
  const n = typeof value === "number" ? value : Number(value);
  return Number.isFinite(n) ? n : fallback;
}

// src/lib/portfolio/metrics.ts
function statsFromClosed(trades) {
  if (!trades.length) {
    return {
      winRate: 0,
      profitFactor: 0,
      avgRMultiple: 0,
      totalTrades: 0,
      realized7d: null,
      realized30d: null
    };
  }
  const wins = trades.filter((t) => t.realizedPnl > 0);
  const losses = trades.filter((t) => t.realizedPnl < 0);
  const grossProfit = wins.reduce((s, t) => s + t.realizedPnl, 0);
  const grossLoss = Math.abs(losses.reduce((s, t) => s + t.realizedPnl, 0));
  const avgLoss = losses.length ? grossLoss / losses.length : 0;
  const rValues = trades.map((t) => {
    if (t.rMultiple != null) return t.rMultiple;
    if (avgLoss > 0) return t.realizedPnl / avgLoss;
    return t.realizedPnl > 0 ? 1 : t.realizedPnl < 0 ? -1 : 0;
  });
  const now = Date.now();
  const inWindow = (days) => trades.filter((t) => now - Date.parse(t.exitDate) <= days * 864e5).reduce((s, t) => s + t.realizedPnl, 0);
  return {
    winRate: wins.length / trades.length * 100,
    profitFactor: grossLoss > 0 ? grossProfit / grossLoss : grossProfit > 0 ? 99 : 0,
    avgRMultiple: rValues.reduce((s, n) => s + n, 0) / rValues.length,
    totalTrades: trades.length,
    realized7d: inWindow(7),
    realized30d: inWindow(30)
  };
}
function buildEquityCurve(closed, currentEquity, realizedAllTime, unrealized) {
  const starting = currentEquity - realizedAllTime - unrealized;
  const sorted = [...closed].sort(
    (a, b) => Date.parse(a.exitDate) - Date.parse(b.exitDate)
  );
  let cum = 0;
  const points = [];
  if (sorted.length) {
    const firstDay = sorted[0].exitDate.slice(0, 10);
    points.push({ date: firstDay, equity: Math.max(0, starting), realizedPnl: 0 });
  }
  for (const t of sorted) {
    cum += t.realizedPnl;
    points.push({
      date: t.exitDate.slice(0, 10),
      equity: Math.max(0, starting + cum),
      realizedPnl: cum
    });
  }
  const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  points.push({
    date: today,
    equity: currentEquity,
    realizedPnl: realizedAllTime
  });
  const byDay = /* @__PURE__ */ new Map();
  for (const p of points) byDay.set(p.date, p);
  return [...byDay.values()].sort((a, b) => a.date.localeCompare(b.date));
}
function drawdownPct(equity, peak) {
  if (peak <= 0) return 0;
  return (equity - peak) / peak * 100;
}
function buildAlerts(equity, cashUsd, positions, ddPct) {
  const alerts = [];
  if (equity <= 0) return alerts;
  const cashPct = cashUsd / equity * 100;
  const ranked = [...positions].sort((a, b) => b.sizeUsd - a.sizeUsd);
  const largest = ranked[0];
  const top3 = ranked.slice(0, 3).reduce((s, p) => s + p.sizeUsd, 0) / equity;
  if (largest && largest.sizeUsd / equity > 0.15) {
    alerts.push({
      id: "size-single",
      level: "warn",
      message: `${largest.symbol} is ${(largest.sizeUsd / equity * 100).toFixed(1)}% of equity (soft cap 15%).`
    });
  }
  if (top3 > 0.45) {
    alerts.push({
      id: "size-top3",
      level: "warn",
      message: `Top 3 names are ${(top3 * 100).toFixed(0)}% of equity (soft cap 45%).`
    });
  }
  if (cashPct < 20) {
    alerts.push({
      id: "cash-floor",
      level: cashPct < 10 ? "crit" : "warn",
      message: `Cash is ${cashPct.toFixed(0)}% \u2014 below the 20% dry-powder floor.`
    });
  }
  if (ddPct < -8) {
    alerts.push({
      id: "drawdown",
      level: ddPct < -15 ? "crit" : "warn",
      message: `Drawdown ${ddPct.toFixed(1)}% from peak \u2014 size down, no new risk.`
    });
  }
  const illiquid = ranked.find(
    (p) => p.liquidityUsd != null && p.liquidityUsd > 0 && p.sizeUsd > p.liquidityUsd * 0.1
  );
  if (illiquid) {
    alerts.push({
      id: "liquidity",
      level: "warn",
      message: `${illiquid.symbol} size is >10% of pool liquidity \u2014 mark-to-market may not be exit-able.`
    });
  }
  return alerts;
}

// src/lib/portfolio/load.ts
var DUST_USD = 5;
var WSOL3 = "So11111111111111111111111111111111111111112";
function tokenField(row) {
  if (row.token && typeof row.token === "object") {
    return {
      symbol: row.token.symbol || row.symbol || "UNKNOWN",
      address: row.token.address || row.token.mint || row.tokenAddress
    };
  }
  return {
    symbol: row.symbol || (typeof row.token === "string" ? row.token : "UNKNOWN"),
    address: row.tokenAddress
  };
}
function isOpenRow(row) {
  const s = (row.status || "").toLowerCase();
  if (s === "closed" || s === "exited" || Boolean(row.closedAt)) return false;
  if (s === "open" || s === "active" || s === "opened") return true;
  return !row.avgExitPrice;
}
function mapOpenPosition(row, markets) {
  const token = tokenField(row);
  const amount = asNumber(row.amount);
  const entry = asNumber(row.avgEntryPrice);
  const livePrice = asNumber(row.priceUsd) || (token.address ? markets.get(token.address)?.priceUsd ?? 0 : 0);
  const cost = asNumber(row.costBasisUsd) || (entry > 0 && amount > 0 ? entry * amount : 0);
  const mtm = livePrice > 0 && amount > 0 ? livePrice * amount : cost;
  const sizeUsd = mtm || cost;
  if (sizeUsd < DUST_USD && asNumber(row.unrealizedPnlUsd) === 0) return null;
  const unrealized = row.unrealizedPnlUsd != null ? asNumber(row.unrealizedPnlUsd) : livePrice && entry ? (livePrice - entry) * amount : 0;
  const market = token.address ? markets.get(token.address) : void 0;
  const opened = row.createdAt || row.openedAt || (/* @__PURE__ */ new Date()).toISOString();
  return {
    id: row.tradeId || row.id || `${token.symbol}-${opened}`,
    token: token.symbol,
    symbol: token.symbol,
    mint: token.address,
    chain: normalizeChain(row.chain, row.networkId ?? (typeof row.token === "object" ? row.token.networkId : void 0)),
    sizeUsd,
    amount,
    entryPrice: entry,
    currentPrice: livePrice || entry,
    entryMcap: asNumber(row.entryMarketCapUsd),
    currentMcap: asNumber(row.marketCapUsd) || market?.marketCapUsd || 0,
    unrealizedPnl: unrealized,
    unrealizedPnlPct: cost > 0 ? unrealized / cost * 100 : 0,
    holdTimeHours: hoursBetween(opened),
    entryDate: opened,
    thesis: row.thesis,
    liquidityUsd: asNumber(row.liquidityUsd) || market?.liquidityUsd || void 0,
    source: "fomo"
  };
}
function mapClosedTrade(row) {
  const token = tokenField(row);
  const entry = asNumber(row.avgEntryPrice);
  const exit = asNumber(row.avgExitPrice);
  const cost = asNumber(row.costBasisUsd);
  const pnl = asNumber(row.realizedPnlUsd);
  const sizeUsd = cost || (entry > 0 && asNumber(row.boughtAmount) > 0 ? entry * asNumber(row.boughtAmount) : Math.abs(pnl));
  const opened = row.createdAt || row.openedAt || row.closedAt || (/* @__PURE__ */ new Date()).toISOString();
  const closed = row.closedAt || opened;
  if (!token.symbol) return null;
  return {
    id: row.tradeId || row.id || `${token.symbol}-${closed}`,
    token: token.symbol,
    symbol: token.symbol,
    mint: token.address,
    chain: normalizeChain(row.chain, row.networkId ?? (typeof row.token === "object" ? row.token.networkId : void 0)),
    side: "long",
    sizeUsd,
    entryPrice: entry,
    exitPrice: exit,
    realizedPnl: pnl,
    realizedPnlPct: sizeUsd > 0 ? pnl / sizeUsd * 100 : 0,
    holdTimeHours: hoursBetween(opened, closed),
    entryDate: opened,
    exitDate: closed
  };
}
function holdingSymbol(h) {
  if (h.token) {
    return {
      symbol: h.token.symbol || h.symbol || "UNKNOWN",
      address: h.token.address || h.token.mint || h.address,
      chain: h.chain,
      networkId: h.token.networkId ?? h.networkId
    };
  }
  return {
    symbol: h.symbol || "UNKNOWN",
    address: h.address,
    chain: h.chain,
    networkId: h.networkId
  };
}
function mapHoldingToPosition(h, markets) {
  const tok = holdingSymbol(h);
  const amount = asNumber(h.amount);
  const price = asNumber(h.priceUsd) || (tok.address ? markets.get(tok.address)?.priceUsd ?? 0 : 0);
  const value = asNumber(h.valueUsd) || amount * price;
  if (value < DUST_USD) return null;
  const market = tok.address ? markets.get(tok.address) : void 0;
  return {
    id: `bal-${tok.address || tok.symbol}`,
    token: tok.symbol,
    symbol: tok.symbol,
    mint: tok.address,
    chain: normalizeChain(tok.chain, tok.networkId),
    sizeUsd: value,
    amount,
    entryPrice: price,
    currentPrice: price,
    entryMcap: market?.marketCapUsd || asNumber(h.marketCapUsd),
    currentMcap: market?.marketCapUsd || asNumber(h.marketCapUsd),
    unrealizedPnl: 0,
    unrealizedPnlPct: 0,
    holdTimeHours: 0,
    entryDate: (/* @__PURE__ */ new Date()).toISOString(),
    liquidityUsd: market?.liquidityUsd || asNumber(h.liquidityUsd) || void 0,
    source: "fomo"
  };
}
function mapOnchainPosition(h, markets, solPrice) {
  const market = markets.get(h.mint);
  const price = h.priceUsd ?? market?.priceUsd ?? (h.mint === WSOL3 || h.native ? solPrice : 0);
  const value = h.valueUsd ?? (price > 0 ? h.amount * price : 0);
  if (value < DUST_USD) return null;
  const symbol = h.symbol || market?.symbol || h.mint.slice(0, 6);
  return {
    id: `onchain-${h.mint}`,
    token: symbol,
    symbol,
    mint: h.mint,
    chain: "solana",
    sizeUsd: value,
    amount: h.amount,
    entryPrice: price,
    currentPrice: price,
    entryMcap: market?.marketCapUsd || 0,
    currentMcap: market?.marketCapUsd || 0,
    unrealizedPnl: 0,
    unrealizedPnlPct: 0,
    holdTimeHours: 0,
    entryDate: (/* @__PURE__ */ new Date()).toISOString(),
    liquidityUsd: market?.liquidityUsd,
    source: "onchain"
  };
}
function mergePositions(fomo, onchain) {
  const byMint = /* @__PURE__ */ new Map();
  const noMint = [];
  for (const p of fomo) {
    if (p.mint) byMint.set(p.mint.toLowerCase(), p);
    else noMint.push(p);
  }
  for (const p of onchain) {
    if (!p.mint) {
      noMint.push(p);
      continue;
    }
    const key = p.mint.toLowerCase();
    const existing = byMint.get(key);
    if (!existing) {
      byMint.set(key, p);
      continue;
    }
    byMint.set(key, {
      ...existing,
      sizeUsd: Math.max(existing.sizeUsd, p.sizeUsd),
      currentPrice: existing.currentPrice || p.currentPrice,
      currentMcap: existing.currentMcap || p.currentMcap,
      liquidityUsd: existing.liquidityUsd || p.liquidityUsd,
      source: "merged"
    });
  }
  return [...byMint.values(), ...noMint];
}
function splitCash(positions) {
  const cash = [];
  const risk = [];
  for (const p of positions) {
    if (isCashAsset(p.symbol, p.mint)) cash.push(p);
    else risk.push(p);
  }
  return { cash, risk };
}
function findRank(traders, handle) {
  const h = handle.replace(/^@/, "").toLowerCase();
  return traders?.find((t) => (t.handle || "").replace(/^@/, "").toLowerCase() === h)?.rank;
}
async function loadPortfolio(input) {
  const handle = input.handle?.replace(/^@/, "").trim();
  const fetchFn = input.fetchFn ?? fetch;
  const warnings = [];
  let user = null;
  let searchHit = null;
  let fomoPositions = [];
  let fomoHoldings = [];
  let closedTotalOnFomo;
  let livePerpPnl = 0;
  let fomoTotalValue;
  let fomoOk = false;
  let rank;
  let solanaWallet = input.solanaWallet?.trim() || void 0;
  let evmWallet = input.evmWallet?.trim() || void 0;
  let onchainPromise;
  const startOnchain = () => {
    if (onchainPromise || !solanaWallet) return;
    onchainPromise = fetchSolanaHoldings({
      owner: solanaWallet,
      rpcUrl: input.solanaRpcUrl,
      heliusApiKey: input.heliusApiKey,
      fetchFn
    });
  };
  if (handle && input.apiKey) {
    const client = createFomoClient({ apiKey: input.apiKey, fetchFn });
    try {
      const found = await client.search(handle);
      const rows = found.results ?? found.traders ?? [];
      searchHit = rows.find(
        (r) => (r.handle || "").replace(/^@/, "").toLowerCase() === handle.toLowerCase()
      ) ?? rows[0] ?? null;
      if (searchHit?.wallets?.solana) solanaWallet = solanaWallet || searchHit.wallets.solana;
      if (searchHit?.wallets?.evm) evmWallet = evmWallet || searchHit.wallets.evm;
      if (searchHit?.handle) fomoOk = true;
      startOnchain();
    } catch (err) {
      if (err instanceof FomoApiError && err.code === "auth") {
        warnings.push("FOMO API key rejected (401). Check FOMO_API_KEY.");
      } else {
        warnings.push(`Search: ${err instanceof Error ? err.message : "failed"}`);
      }
    }
    const fomoKey = searchHit?.userId || handle;
    const results = await Promise.allSettled([
      client.resolveUser(handle),
      client.positions(fomoKey),
      client.balances(fomoKey),
      client.leaderboard("all")
    ]);
    const take = (i, label) => {
      const r = results[i];
      if (r.status === "fulfilled") return r.value;
      const err = r.reason;
      if (err instanceof FomoApiError) {
        if (err.code === "auth") warnings.push("FOMO API key rejected (401). Check FOMO_API_KEY.");
        else if (err.code === "credits") warnings.push("FOMO API credits exhausted (402). Wallet path still runs.");
        else if (err.code === "not_found") warnings.push(`FOMO handle @${handle} was not found.`);
        else warnings.push(`${label}: ${err.message}`);
      } else {
        warnings.push(`${label}: ${err instanceof Error ? err.message : "failed"}`);
      }
      return null;
    };
    user = take(0, "Profile");
    const pos = take(1, "Positions");
    const bal = take(2, "Balances");
    const board = take(3, "Leaderboard");
    if (user && !user.error) fomoOk = true;
    if (user?.wallets?.solana) solanaWallet = solanaWallet || user.wallets.solana;
    if (user?.wallets?.evm || user?.wallets?.ethereum) {
      evmWallet = evmWallet || user.wallets.evm || user.wallets.ethereum || void 0;
    }
    startOnchain();
    if (pos) {
      fomoPositions = pos.positions ?? pos.trades ?? pos.items ?? [];
      closedTotalOnFomo = pos.closedTotalOnFomo;
      if (pos.available === false && !fomoPositions.length) {
        warnings.push("FOMO has not captured trade history for this handle yet \u2014 using on-chain balances.");
      }
    }
    if (bal) {
      fomoHoldings = bal.holdings ?? bal.balances ?? [];
      fomoTotalValue = bal.totalValueUsd;
      const perp = bal.livePerpPnl;
      livePerpPnl = typeof perp === "number" ? perp : asNumber(perp?.usd);
      if (bal.available === false && !fomoHoldings.length) {
        warnings.push("FOMO holdings feed is empty right now; on-chain mark-to-market is the live book.");
      }
    }
    rank = findRank(board?.traders, handle);
  } else if (handle && !input.apiKey) {
    warnings.push("Set FOMO_API_KEY (or paste a key in Settings) to pull FOMO PnL, trades, and social stats.");
  } else if (!handle) {
    warnings.push("No FOMO handle set \u2014 running wallet / on-chain path only.");
  }
  let onchain = [];
  let onchainOk = false;
  startOnchain();
  if (onchainPromise) {
    try {
      onchain = await onchainPromise;
      onchainOk = true;
    } catch (err) {
      warnings.push(
        `Solana wallet read failed: ${err instanceof Error ? err.message : "RPC error"}`
      );
    }
  } else {
    warnings.push("No Solana wallet yet. FOMO resolution or a manual address is required to mark-to-market on-chain.");
  }
  const mints = [
    ...fomoPositions.map((p) => tokenField(p).address),
    ...fomoHoldings.map((h) => holdingSymbol(h).address),
    ...onchain.map((h) => h.mint)
  ].filter((m) => Boolean(m));
  const [markets, solPrice] = await Promise.all([
    fetchDexMarkets(mints, fetchFn),
    fetchSolPriceUsd(fetchFn)
  ]);
  const openFromFomo = fomoPositions.filter(isOpenRow).map((p) => mapOpenPosition(p, markets)).filter((p) => Boolean(p));
  const closed = fomoPositions.filter((p) => {
    const s = (p.status || "").toLowerCase();
    return s === "closed" || Boolean(p.closedAt);
  }).map(mapClosedTrade).filter((t) => Boolean(t));
  const fromBalances = fomoHoldings.map((h) => mapHoldingToPosition(h, markets)).filter((p) => Boolean(p));
  const fromChain = onchain.map((h) => mapOnchainPosition(h, markets, solPrice)).filter((p) => Boolean(p));
  const merged = mergePositions(
    openFromFomo.length ? openFromFomo : fromBalances,
    fromChain
  );
  const { cash, risk } = splitCash(merged);
  const cashUsd = cash.reduce((s, p) => s + p.sizeUsd, 0);
  const openPositionsValue = risk.reduce((s, p) => s + p.sizeUsd, 0);
  const fomoUnrealized = openFromFomo.reduce((s, p) => s + p.unrealizedPnl, 0);
  const unrealized = fomoUnrealized + livePerpPnl;
  const chainTotal = [...cash, ...risk].reduce((s, p) => s + p.sizeUsd, 0);
  const totalEquity = fomoTotalValue && fomoTotalValue > 0 ? fomoTotalValue + (livePerpPnl || 0) : chainTotal || openPositionsValue + cashUsd;
  const pnlWindows = {
    h24: user?.pnl?.["24h"] ?? null,
    d7: user?.pnl?.["7d"] ?? null,
    d30: user?.pnl?.["30d"] ?? null,
    all: user?.pnl?.all ?? user?.pnlUsd ?? null
  };
  const closedStats = statsFromClosed(closed);
  const realizedAllTime = pnlWindows.all ?? closed.reduce((s, t) => s + t.realizedPnl, 0);
  const equityCurve = buildEquityCurve(closed, totalEquity, realizedAllTime, unrealized);
  const peakEquity = Math.max(totalEquity, ...equityCurve.map((p) => p.equity), 0);
  const currentDrawdownPct = drawdownPct(totalEquity, peakEquity);
  const alerts = buildAlerts(totalEquity, cashUsd, risk, currentDrawdownPct);
  const followers = asNumber(user?.followers ?? user?.profile?.followers);
  const avgHold = user?.averageHoldTimeSeconds ?? user?.profile?.averageHoldTimeSeconds;
  return {
    handle: user?.handle || user?.userHandle || searchHit?.handle || handle,
    displayName: user?.displayName || searchHit?.displayName,
    wallets: { solana: solanaWallet, evm: evmWallet },
    source: {
      fomo: fomoOk,
      onchain: onchainOk,
      fetchedAt: (/* @__PURE__ */ new Date()).toISOString(),
      warnings
    },
    summary: {
      totalEquity,
      cashUsd,
      openPositionsValue,
      realizedPnlAllTime: realizedAllTime,
      realizedPnl7d: pnlWindows.d7 ?? closedStats.realized7d,
      realizedPnl30d: pnlWindows.d30 ?? closedStats.realized30d,
      unrealizedPnl: unrealized,
      peakEquity,
      currentDrawdownPct,
      winRate: closedStats.winRate,
      profitFactor: closedStats.profitFactor,
      avgRMultiple: closedStats.avgRMultiple,
      totalTrades: closedTotalOnFomo || asNumber(user?.trades ?? user?.numTrades) || closedStats.totalTrades,
      closedTradesCaptured: closed.length,
      followers,
      leaderboardRank: rank
    },
    influence: {
      followers,
      following: user?.following ?? user?.profile?.following ?? null,
      leaderboardRank: rank,
      rankWindow: rank != null ? "all" : void 0,
      averageHoldTimeHours: avgHold != null ? avgHold / 3600 : void 0,
      accountAgeDays: user?.accountAgeDays ?? user?.profile?.accountAgeDays
    },
    pnlWindows,
    openPositions: [...risk].sort((a, b) => b.sizeUsd - a.sizeUsd),
    closedTrades: closed.sort((a, b) => Date.parse(b.exitDate) - Date.parse(a.exitDate)),
    equityCurve,
    alerts
  };
}

// server/vercel-portfolio.ts
var config = {
  maxDuration: 60
};
function first(value) {
  if (Array.isArray(value)) return value[0] || "";
  return value || "";
}
function headerValue(headers2, name) {
  if (headers2 && typeof headers2.get === "function") {
    return headers2.get(name) || "";
  }
  const rec = headers2;
  return first(rec[name] || rec[name.toLowerCase()]);
}
function queryValue(req, name) {
  if (req.query) return first(req.query[name]);
  try {
    const url = new URL(req.url || "", "http://localhost");
    return url.searchParams.get(name) || "";
  } catch {
    return "";
  }
}
function json(res, status, body) {
  res.setHeader?.("content-type", "application/json; charset=utf-8");
  res.setHeader?.("cache-control", "no-store");
  res.status(status).json(body);
}
async function handler(req, res) {
  try {
    if (req.method === "OPTIONS") {
      res.status(204).end();
      return;
    }
    const handle = queryValue(req, "handle") || process.env.FOMO_HANDLE || process.env.VITE_FOMO_HANDLE || "";
    const solanaWallet = queryValue(req, "solana") || process.env.SOLANA_WALLET || process.env.VITE_SOLANA_WALLET || "";
    const evmWallet = queryValue(req, "evm") || process.env.EVM_WALLET || process.env.VITE_EVM_WALLET || "";
    const apiKey = headerValue(req.headers, "x-fomo-api-key") || process.env.FOMO_API_KEY || process.env.VITE_FOMO_API_KEY || "";
    if (!handle && !solanaWallet) {
      json(res, 400, {
        error: "config",
        message: "Set a FOMO handle and/or a Solana wallet in Settings, or FOMO_HANDLE / SOLANA_WALLET in the environment."
      });
      return;
    }
    const snapshot = await loadPortfolio({
      handle,
      apiKey,
      solanaWallet,
      evmWallet,
      solanaRpcUrl: process.env.SOLANA_RPC_URL,
      heliusApiKey: process.env.HELIUS_API_KEY
    });
    json(res, 200, snapshot);
  } catch (err) {
    json(res, 502, {
      error: "upstream",
      message: err instanceof Error ? err.message : "Failed to load portfolio"
    });
  }
}
export {
  config,
  handler as default
};
