/* generated by scripts/bundle-api.mjs — do not edit */

// src/lib/fomo/client.ts
var DEFAULT_BASE = "https://api.fomoapi.io";
var FomoApiError = class extends Error {
  status;
  code;
  body;
  constructor(status, message, body) {
    super(message);
    this.status = status;
    this.body = body;
    if (status === 401) this.code = "auth";
    else if (status === 402) this.code = "credits";
    else if (status === 404) this.code = "not_found";
    else this.code = "upstream";
  }
};
function headers(apiKey) {
  return {
    authorization: `Bearer ${apiKey}`,
    accept: "application/json"
  };
}
async function getJson(fetchFn, url, apiKey, timeoutMs = 45e3) {
  const res = await fetchFn(url, {
    headers: headers(apiKey),
    signal: AbortSignal.timeout(timeoutMs)
  });
  const text = await res.text();
  let body = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = { raw: text.slice(0, 400) };
  }
  if (!res.ok) {
    const errObj = body;
    throw new FomoApiError(
      res.status,
      errObj?.message || errObj?.error || `FOMO API ${res.status}`,
      body
    );
  }
  return body;
}
function createFomoClient(opts) {
  const base = (opts.baseUrl || DEFAULT_BASE).replace(/\/$/, "");
  const fetchFn = opts.fetchFn ?? fetch;
  const key2 = opts.apiKey;
  return {
    resolveUser(handle) {
      const h = encodeURIComponent(handle.replace(/^@/, ""));
      return getJson(fetchFn, `${base}/v2/users/${h}`, key2, 9e4);
    },
    search(query) {
      const q = encodeURIComponent(query.replace(/^@/, ""));
      return getJson(
        fetchFn,
        `${base}/v2/search?q=${q}&type=traders&limit=5`,
        key2,
        2e4
      );
    },
    positions(handle, query = "deep=1&limit=500") {
      const h = encodeURIComponent(handle.replace(/^@/, ""));
      return getJson(
        fetchFn,
        `${base}/v2/users/${h}/positions?${query}`,
        key2,
        45e3
      );
    },
    balances(handle) {
      const h = encodeURIComponent(handle.replace(/^@/, ""));
      return getJson(
        fetchFn,
        `${base}/v2/users/${h}/balances`,
        key2,
        45e3
      );
    },
    leaderboard(window = "all", limit = 150) {
      return getJson(
        fetchFn,
        `${base}/v2/leaderboard/${window}?limit=${limit}`,
        key2,
        3e4
      );
    },
    spotlight(handle) {
      const h = encodeURIComponent(handle.replace(/^@/, ""));
      return getJson(fetchFn, `${base}/v2/users/${h}/spotlight`, key2, 2e4);
    },
    relaySwaps(handle) {
      const h = encodeURIComponent(handle.replace(/^@/, ""));
      return getJson(
        fetchFn,
        `${base}/v2/users/${h}/swaps?source=relay&limit=100`,
        key2,
        3e4
      );
    }
  };
}

// src/lib/wallet/markets.ts
var DEX_TOKENS = "https://api.dexscreener.com/latest/dex/tokens";
function pickBestPair(pairs, mint) {
  const lower = mint.toLowerCase();
  const relevant = pairs.filter((p) => p.baseToken?.address?.toLowerCase() === lower);
  return [...relevant].sort(
    (a, b) => (b.liquidity?.usd ?? 0) - (a.liquidity?.usd ?? 0)
  )[0];
}
async function fetchDexMarkets(mints, fetchFn = fetch) {
  const out = /* @__PURE__ */ new Map();
  const unique = [...new Set(mints.filter(Boolean))];
  const groups = [unique.filter((m) => m.startsWith("0x")), unique.filter((m) => !m.startsWith("0x"))];
  const chunkSize = 10;
  for (const group of groups) {
    for (let i = 0; i < group.length; i += chunkSize) {
      const chunk = group.slice(i, i + chunkSize);
      if (!chunk.length) continue;
      const url = `${DEX_TOKENS}/${chunk.join(",")}`;
      try {
        const res = await fetchFn(url, { signal: AbortSignal.timeout(15e3) });
        if (!res.ok) continue;
        const body = await res.json();
        const pairs = Array.isArray(body) ? body : body.pairs ?? [];
        for (const mint of chunk) {
          const best = pickBestPair(pairs, mint);
          if (!best?.priceUsd) continue;
          const priceUsd = Number(best.priceUsd);
          if (!Number.isFinite(priceUsd)) continue;
          const isBase = best.baseToken?.address?.toLowerCase() === mint.toLowerCase();
          const change24hPct = Number(best.priceChange?.h24);
          const row = {
            priceUsd,
            marketCapUsd: Number(best.marketCap || best.fdv || 0) || 0,
            liquidityUsd: Number(best.liquidity?.usd || 0) || 0,
            change24hPct: Number.isFinite(change24hPct) ? change24hPct : void 0,
            volume24hUsd: Number(best.volume?.h24) || void 0,
            symbol: isBase ? best.baseToken?.symbol : best.quoteToken?.symbol,
            name: isBase ? best.baseToken?.name : best.quoteToken?.name,
            quoteSymbol: isBase ? best.quoteToken?.symbol : best.baseToken?.symbol
          };
          out.set(mint, row);
          out.set(mint.toLowerCase(), row);
        }
      } catch {
      }
    }
  }
  return out;
}
async function fetchSolPriceUsd(fetchFn = fetch) {
  try {
    const res = await fetchFn(
      "https://api.geckoterminal.com/api/v2/simple/networks/solana/token_price/So11111111111111111111111111111111111111112",
      { signal: AbortSignal.timeout(1e4) }
    );
    if (!res.ok) return 0;
    const body = await res.json();
    const raw = body.data?.attributes?.token_prices?.["So11111111111111111111111111111111111111112"];
    const n = Number(raw);
    return Number.isFinite(n) ? n : 0;
  } catch {
    return 0;
  }
}

// src/lib/wallet/solana.ts
var TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
var TOKEN_2022_PROGRAM = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
var WSOL = "So11111111111111111111111111111111111111112";
var RPC_CANDIDATES = [
  "https://api.mainnet-beta.solana.com",
  "https://solana-rpc.publicnode.com"
];
async function rpc(url, method, params, fetchFn) {
  const res = await fetchFn(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
    signal: AbortSignal.timeout(2e4)
  });
  const text = await res.text();
  let body;
  try {
    body = text ? JSON.parse(text) : {};
  } catch {
    throw new Error(`Solana RPC HTTP ${res.status}`);
  }
  if (!res.ok) throw new Error(body.error?.message || `Solana RPC HTTP ${res.status}`);
  if (body.error) throw new Error(body.error.message || "Solana RPC error");
  return body.result;
}
async function rpcWithFallback(urls, method, params, fetchFn) {
  let last = new Error("No Solana RPC endpoints");
  for (const url of urls) {
    try {
      return await rpc(url, method, params, fetchFn);
    } catch (err) {
      last = err instanceof Error ? err : new Error(String(err));
    }
  }
  throw last;
}
function rpcList(preferred) {
  const urls = preferred ? [preferred, ...RPC_CANDIDATES] : [...RPC_CANDIDATES];
  return [...new Set(urls)];
}
async function tokenAccounts(rpcUrls, owner, programId, fetchFn) {
  const result = await rpcWithFallback(
    rpcUrls,
    "getTokenAccountsByOwner",
    [owner, { programId }, { encoding: "jsonParsed" }],
    fetchFn
  );
  return (result.value ?? []).map((row) => {
    const info = row.account.data.parsed.info;
    return {
      mint: info.mint,
      amount: Number(info.tokenAmount.uiAmount ?? 0),
      decimals: info.tokenAmount.decimals,
      chain: "solana"
    };
  }).filter((h) => h.amount > 0);
}
function collapseByMint(rows) {
  const map = /* @__PURE__ */ new Map();
  for (const h of rows) {
    const prev = map.get(h.mint);
    if (!prev) {
      map.set(h.mint, { ...h });
      continue;
    }
    prev.amount += h.amount;
    prev.native = Boolean(prev.native || h.native);
    if (h.valueUsd != null || prev.valueUsd != null) {
      prev.valueUsd = (prev.valueUsd ?? 0) + (h.valueUsd ?? 0);
    }
    prev.symbol = prev.native ? "SOL" : prev.symbol || h.symbol;
  }
  return [...map.values()];
}
async function fetchSolanaHoldings(opts) {
  const fetchFn = opts.fetchFn ?? fetch;
  if (opts.heliusApiKey) {
    try {
      return await fetchHeliusHoldings(opts.owner, opts.heliusApiKey, fetchFn);
    } catch {
    }
  }
  const rpcUrls = rpcList(opts.rpcUrl);
  const [lamports, spl, t22] = await Promise.all([
    rpcWithFallback(rpcUrls, "getBalance", [opts.owner], fetchFn),
    tokenAccounts(rpcUrls, opts.owner, TOKEN_PROGRAM, fetchFn),
    tokenAccounts(rpcUrls, opts.owner, TOKEN_2022_PROGRAM, fetchFn).catch(
      () => []
    )
  ]);
  const native = {
    mint: WSOL,
    amount: lamports.value / 1e9,
    decimals: 9,
    symbol: "SOL",
    name: "Solana",
    chain: "solana",
    native: true
  };
  const wrappedSol = [...spl, ...t22].filter((h) => h.mint === WSOL).reduce((s, h) => s + h.amount, 0);
  native.amount += wrappedSol;
  const tokens = collapseByMint([...spl, ...t22].filter((h) => h.mint !== WSOL));
  return collapseByMint(native.amount > 0 ? [native, ...tokens] : tokens);
}
async function fetchHeliusHoldings(owner, apiKey, fetchFn) {
  const url = `https://mainnet.helius-rpc.com/?api-key=${apiKey}`;
  const res = await fetchFn(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 1,
      method: "getAssetsByOwner",
      params: {
        ownerAddress: owner,
        page: 1,
        limit: 1e3,
        displayOptions: { showFungible: true, showNativeBalance: true }
      }
    }),
    signal: AbortSignal.timeout(2e4)
  });
  const body = await res.json();
  if (body.error) throw new Error(body.error.message || "Helius error");
  const data = body.result ?? {};
  const out = [];
  const lamports = data.nativeBalance?.lamports ?? 0;
  if (lamports > 0) {
    out.push({
      mint: WSOL,
      amount: lamports / 1e9,
      decimals: 9,
      symbol: "SOL",
      name: "Solana",
      priceUsd: data.nativeBalance?.price_per_sol,
      valueUsd: data.nativeBalance?.price_per_sol != null ? lamports / 1e9 * data.nativeBalance.price_per_sol : void 0,
      chain: "solana",
      native: true
    });
  }
  for (const item of data.items ?? []) {
    const info = item.token_info;
    if (!info || !item.id) continue;
    const decimals = info.decimals ?? 0;
    const raw = Number(info.balance ?? 0);
    const amount = decimals >= 0 ? raw / 10 ** decimals : raw;
    if (amount <= 0) continue;
    const price = info.price_info?.price_per_token;
    out.push({
      mint: item.id,
      amount,
      decimals,
      symbol: info.symbol || item.content?.metadata?.symbol,
      name: item.content?.metadata?.name,
      priceUsd: price,
      valueUsd: info.price_info?.total_price ?? (price != null ? amount * price : void 0),
      chain: "solana"
    });
  }
  return collapseByMint(out);
}

// src/lib/portfolio/helpers.ts
var STABLE_SYMBOLS = /* @__PURE__ */ new Set([
  "USDC",
  "USDT",
  "USD1",
  "PYUSD",
  "USDS",
  "DAI",
  "FDUSD",
  "CASH",
  "USD",
  "USDC.E"
]);
var STABLE_MINTS = /* @__PURE__ */ new Set([
  "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  // USDC
  "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
  // USDT
  "USD1ttGY1N17NEEHLmELoaybftRBUSErhqYiQzvEmuB",
  "2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo"
  // PYUSD
]);
var WSOL2 = "So11111111111111111111111111111111111111112";
function isCashAsset(symbol, mint) {
  const sym = (symbol || "").toUpperCase();
  if (sym === "SOL" || sym === "WSOL") return true;
  if (STABLE_SYMBOLS.has(sym)) return true;
  if (mint && (mint === WSOL2 || STABLE_MINTS.has(mint))) return true;
  return false;
}
function normalizeChain(raw, networkId) {
  const s = (raw || "").toLowerCase();
  if (networkId === 1399811149 || s.includes("sol")) return "solana";
  if (networkId === 8453 || s.includes("base")) return "base";
  if (networkId === 56 || s.includes("bnb") || s.includes("bsc")) return "bnb";
  if (networkId === 1 || s === "eth" || s.includes("ethereum")) return "ethereum";
  if (networkId === 4663 || s.includes("robin") || s.includes("hood")) return "robinhood";
  if (networkId === 143 || s.includes("monad")) return "monad";
  if (s.includes("hyper")) return "hyperliquid";
  return "other";
}
function hoursBetween(from, to) {
  if (!from) return 0;
  const a = Date.parse(from);
  const b = to ? Date.parse(to) : Date.now();
  if (!Number.isFinite(a) || !Number.isFinite(b)) return 0;
  return Math.max(0, (b - a) / 36e5);
}
function asNumber(value, fallback = 0) {
  const n = typeof value === "number" ? value : Number(value);
  return Number.isFinite(n) ? n : fallback;
}
function pnlFromChangePct(valueUsd, changePct) {
  if (changePct == null || !Number.isFinite(changePct) || changePct <= -99.999) return 0;
  return valueUsd * (changePct / (100 + changePct));
}
function inferredEntryMcap(currentMcap, entryPrice, currentPrice) {
  if (currentMcap <= 0 || entryPrice <= 0 || currentPrice <= 0) return 0;
  return currentMcap * (entryPrice / currentPrice);
}

// src/lib/portfolio/metrics.ts
function statsFromClosed(trades) {
  if (!trades.length) {
    return {
      winRate: 0,
      profitFactor: 0,
      avgRMultiple: 0,
      totalTrades: 0,
      realized7d: null,
      realized30d: null
    };
  }
  const wins = trades.filter((t) => t.realizedPnl > 0);
  const losses = trades.filter((t) => t.realizedPnl < 0);
  const grossProfit = wins.reduce((s, t) => s + t.realizedPnl, 0);
  const grossLoss = Math.abs(losses.reduce((s, t) => s + t.realizedPnl, 0));
  const avgLoss = losses.length ? grossLoss / losses.length : 0;
  const rValues = trades.map((t) => {
    if (t.rMultiple != null) return t.rMultiple;
    if (avgLoss > 0) return t.realizedPnl / avgLoss;
    return t.realizedPnl > 0 ? 1 : t.realizedPnl < 0 ? -1 : 0;
  });
  const now = Date.now();
  const inWindow = (days) => trades.filter((t) => now - Date.parse(t.exitDate) <= days * 864e5).reduce((s, t) => s + t.realizedPnl, 0);
  return {
    winRate: wins.length / trades.length * 100,
    profitFactor: grossLoss > 0 ? grossProfit / grossLoss : grossProfit > 0 ? 99 : 0,
    avgRMultiple: rValues.reduce((s, n) => s + n, 0) / rValues.length,
    totalTrades: trades.length,
    realized7d: inWindow(7),
    realized30d: inWindow(30)
  };
}
function buildEquityCurve(closed, currentEquity, realizedAllTime, unrealized) {
  const starting = currentEquity - realizedAllTime - unrealized;
  const sorted = [...closed].sort(
    (a, b) => Date.parse(a.exitDate) - Date.parse(b.exitDate)
  );
  let cum = 0;
  const points = [];
  if (sorted.length) {
    const firstDay = sorted[0].exitDate.slice(0, 10);
    points.push({ date: firstDay, equity: Math.max(0, starting), realizedPnl: 0 });
  }
  for (const t of sorted) {
    cum += t.realizedPnl;
    points.push({
      date: t.exitDate.slice(0, 10),
      equity: Math.max(0, starting + cum),
      realizedPnl: cum
    });
  }
  const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  points.push({
    date: today,
    equity: currentEquity,
    realizedPnl: realizedAllTime
  });
  const byDay = /* @__PURE__ */ new Map();
  for (const p of points) byDay.set(p.date, p);
  return [...byDay.values()].sort((a, b) => a.date.localeCompare(b.date));
}
function drawdownPct(equity, peak) {
  if (peak <= 0) return 0;
  return (equity - peak) / peak * 100;
}
function buildAlerts(equity, cashUsd, positions, ddPct) {
  const alerts = [];
  if (equity <= 0) return alerts;
  const cashPct = cashUsd / equity * 100;
  const ranked = [...positions].sort((a, b) => b.sizeUsd - a.sizeUsd);
  const largest = ranked[0];
  const top3 = ranked.slice(0, 3).reduce((s, p) => s + p.sizeUsd, 0) / equity;
  if (largest && largest.sizeUsd / equity > 0.15) {
    alerts.push({
      id: "size-single",
      level: "warn",
      message: `${largest.symbol} is ${(largest.sizeUsd / equity * 100).toFixed(1)}% of equity (soft cap 15%).`
    });
  }
  if (top3 > 0.45) {
    alerts.push({
      id: "size-top3",
      level: "warn",
      message: `Top 3 names are ${(top3 * 100).toFixed(0)}% of equity (soft cap 45%).`
    });
  }
  if (cashPct < 20) {
    alerts.push({
      id: "cash-floor",
      level: cashPct < 10 ? "crit" : "warn",
      message: `Cash is ${cashPct.toFixed(0)}% \u2014 below the 20% dry-powder floor.`
    });
  }
  if (ddPct < -8) {
    alerts.push({
      id: "drawdown",
      level: ddPct < -15 ? "crit" : "warn",
      message: `Drawdown ${ddPct.toFixed(1)}% from peak \u2014 size down, no new risk.`
    });
  }
  const illiquid = ranked.find(
    (p) => p.liquidityUsd != null && p.liquidityUsd > 0 && p.sizeUsd > p.liquidityUsd * 0.1
  );
  if (illiquid) {
    alerts.push({
      id: "liquidity",
      level: "warn",
      message: `${illiquid.symbol} size is >10% of pool liquidity \u2014 mark-to-market may not be exit-able.`
    });
  }
  return alerts;
}

// src/lib/portfolio/relayPositions.ts
var DUST_USD = 5;
function tokenKey(address, symbol, chainId) {
  return `${(address || symbol || "").toLowerCase()}::${chainId ?? ""}`;
}
function earlier(a, b) {
  if (!a) return b;
  if (!b) return a;
  return Date.parse(a) <= Date.parse(b) ? a : b;
}
function later(a, b) {
  if (!a) return b;
  if (!b) return a;
  return Date.parse(a) >= Date.parse(b) ? a : b;
}
function accumulate(swaps) {
  const map = /* @__PURE__ */ new Map();
  const bump = (token, chain, fallbackChainId, at, side) => {
    if (!token) return;
    const symbol = token.symbol || "UNKNOWN";
    const address = token.address || symbol;
    const chainId = token.chainId ?? fallbackChainId;
    const key2 = tokenKey(address, symbol, chainId);
    const prev = map.get(key2) ?? {
      symbol,
      address,
      chain,
      chainId,
      boughtAmount: 0,
      boughtUsd: 0,
      boughtUsdNow: 0,
      soldAmount: 0,
      soldUsd: 0,
      lastAt: at
    };
    const amount = asNumber(token.amount);
    const usd = asNumber(token.usd);
    const usdNow = asNumber(token.usdNow);
    if (side === "buy") {
      prev.boughtAmount += amount;
      prev.boughtUsd += usd;
      prev.boughtUsdNow += usdNow || usd;
      prev.firstBuyAt = earlier(prev.firstBuyAt, at);
    } else {
      prev.soldAmount += amount;
      prev.soldUsd += usd;
      prev.lastSellAt = later(prev.lastSellAt, at);
    }
    prev.chain = prev.chain || chain;
    prev.lastAt = later(prev.lastAt, at);
    map.set(key2, prev);
  };
  for (const swap of swaps) {
    bump(swap.tokenOut, swap.toChain || swap.chain, swap.chainId, swap.at, "buy");
    bump(swap.tokenIn, swap.fromChain || swap.chain, swap.tokenIn?.chainId ?? swap.chainId, swap.at, "sell");
  }
  return map;
}
function positionsFromRelaySwaps(swaps) {
  const out = [];
  for (const row of accumulate(swaps).values()) {
    const remaining = row.boughtAmount - row.soldAmount;
    if (remaining <= 0) continue;
    const frac = row.boughtAmount > 0 ? remaining / row.boughtAmount : 0;
    const cost = row.boughtUsd * frac;
    const value = (row.boughtUsdNow > 0 ? row.boughtUsdNow : row.boughtUsd) * frac;
    if (value < DUST_USD && !isCashAsset(row.symbol, row.address)) continue;
    const entry = remaining > 0 ? cost / remaining : 0;
    const price = remaining > 0 ? value / remaining : 0;
    const unrealized = value - cost;
    out.push({
      id: `relay-${row.address}`,
      token: row.symbol,
      symbol: row.symbol,
      mint: row.address,
      chain: normalizeChain(row.chain, row.chainId),
      sizeUsd: value,
      amount: remaining,
      entryPrice: entry,
      currentPrice: price,
      entryMcap: 0,
      currentMcap: 0,
      unrealizedPnl: unrealized,
      unrealizedPnlPct: cost > 0 ? unrealized / cost * 100 : 0,
      holdTimeHours: hoursBetween(row.firstBuyAt),
      entryDate: row.firstBuyAt || row.lastAt || (/* @__PURE__ */ new Date()).toISOString(),
      source: "fomo",
      hasCostBasis: cost > 0
    });
  }
  return out;
}
function closedFromRelaySwaps(swaps) {
  const out = [];
  for (const row of accumulate(swaps).values()) {
    if (isCashAsset(row.symbol, row.address)) continue;
    if (row.boughtAmount <= 0 || row.soldAmount <= 0) continue;
    const matched = Math.min(row.soldAmount, row.boughtAmount);
    const soldFrac = matched / row.boughtAmount;
    const cost = row.boughtUsd * soldFrac;
    if (cost <= 0) continue;
    const proceeds = row.soldUsd * (matched / row.soldAmount);
    const realized = proceeds - cost;
    const remainingFrac = 1 - soldFrac;
    const entryPrice = row.boughtUsd / row.boughtAmount;
    const exitPrice = proceeds / matched;
    out.push({
      id: `relay-close-${row.address}`,
      token: row.symbol,
      symbol: row.symbol,
      mint: row.address,
      chain: normalizeChain(row.chain, row.chainId),
      side: "long",
      sizeUsd: cost,
      entryPrice,
      exitPrice,
      realizedPnl: realized,
      realizedPnlPct: realized / cost * 100,
      holdTimeHours: hoursBetween(row.firstBuyAt, row.lastSellAt),
      entryDate: row.firstBuyAt || row.lastAt || (/* @__PURE__ */ new Date()).toISOString(),
      exitDate: row.lastSellAt || row.lastAt || (/* @__PURE__ */ new Date()).toISOString(),
      notes: remainingFrac > 0.01 ? "partial exit (Relay)" : "Relay"
    });
  }
  return out;
}

// src/lib/relay/api.ts
var RELAY_REQUESTS = "https://api.relay.link/requests/v2";
var RELAY_SOLANA_CHAIN_ID = 792703809;
function chainName(chainId) {
  if (chainId === RELAY_SOLANA_CHAIN_ID) return "solana";
  if (chainId === 4663) return "robinhood";
  if (chainId === 8453) return "base";
  if (chainId === 56) return "bnb";
  if (chainId === 1) return "ethereum";
  return void 0;
}
function toToken(c) {
  if (!c?.currency) return void 0;
  const amount = Number(c.amountFormatted);
  const usd = Number(c.amountUsd);
  const usdNow = Number(c.amountUsdCurrent);
  return {
    address: c.currency.address,
    symbol: c.currency.symbol,
    chainId: c.currency.chainId,
    amount: Number.isFinite(amount) ? amount : 0,
    usd: Number.isFinite(usd) ? usd : 0,
    usdNow: Number.isFinite(usdNow) ? usdNow : void 0
  };
}
function swapsFromRelayRequests(requests) {
  const swaps = [];
  const recipients = /* @__PURE__ */ new Map();
  for (const r of requests) {
    if (r.status !== "success") continue;
    const m = r.data?.metadata;
    const tokenIn = toToken(m?.currencyIn);
    const tokenOut = toToken(m?.currencyOut);
    if (!tokenIn || !tokenOut) continue;
    const recipient = m?.recipient || r.recipient;
    if (recipient?.startsWith("0x")) {
      recipients.set(recipient.toLowerCase(), (recipients.get(recipient.toLowerCase()) ?? 0) + 1);
    }
    swaps.push({
      swapId: r.id,
      fromChain: chainName(tokenIn.chainId),
      toChain: chainName(tokenOut.chainId),
      chainId: tokenOut.chainId,
      tokenIn,
      tokenOut,
      status: r.status,
      at: r.createdAt,
      source: "relay"
    });
  }
  const evmWallet = [...recipients.entries()].sort((a, b) => b[1] - a[1])[0]?.[0];
  return { swaps, evmWallet, truncated: false };
}
var HISTORY_TTL_MS = 3 * 6e4;
var historyCache = /* @__PURE__ */ new Map();
async function fetchRelayHistory(user, fetchFn = fetch, maxPages = 8, deadlineAt = Number.POSITIVE_INFINITY) {
  const key2 = user.toLowerCase();
  const cached = historyCache.get(key2);
  const fresh = cached && Date.now() - cached.at < HISTORY_TTL_MS;
  if (fresh && !cached.history.rateLimited) return cached.history;
  try {
    const history = await fetchRelayPages(user, fetchFn, maxPages, deadlineAt);
    if (cached && history.rateLimited && cached.history.swaps.length > history.swaps.length) {
      return cached.history;
    }
    historyCache.set(key2, { at: Date.now(), history });
    return history;
  } catch (err) {
    if (cached) return cached.history;
    throw err;
  }
}
async function fetchRelayPages(user, fetchFn, maxPages, deadlineAt) {
  const all = [];
  let continuation;
  let pages = 0;
  let stoppedEarly = false;
  do {
    if (all.length && Date.now() > deadlineAt) {
      stoppedEarly = true;
      break;
    }
    const params = new URLSearchParams({ user, limit: "50" });
    if (continuation) params.set("continuation", continuation);
    const body = await fetchPage(`${RELAY_REQUESTS}?${params}`, fetchFn, deadlineAt);
    if (!body) {
      if (!all.length) throw new Error("Relay rate-limited or unavailable");
      stoppedEarly = true;
      break;
    }
    all.push(...body.requests ?? []);
    continuation = body.continuation || void 0;
    pages += 1;
  } while (continuation && pages < maxPages);
  const history = swapsFromRelayRequests(all);
  return { ...history, truncated: stoppedEarly || Boolean(continuation), rateLimited: stoppedEarly };
}
var sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function fetchPage(url, fetchFn, deadlineAt = Number.POSITIVE_INFINITY) {
  for (let attempt = 0; attempt < 4; attempt++) {
    let wait = 800 * 2 ** attempt;
    try {
      const res = await fetchFn(url, { signal: AbortSignal.timeout(12e3) });
      if (res.ok) return await res.json();
      if (res.status !== 429 && res.status < 500) return null;
      const retryAfter = Number(res.headers.get("retry-after"));
      if (Number.isFinite(retryAfter) && retryAfter > 0) wait = Math.min(retryAfter, 5) * 1e3;
    } catch {
    }
    if (Date.now() + wait > deadlineAt) return null;
    await sleep(wait);
  }
  return null;
}

// src/lib/launchpad/classify.ts
var DEX_TO_LAUNCHPAD = {
  "pons-v2": { id: "pons", label: "Pons" },
  "pons-v2-dex": { id: "pons", label: "Pons" },
  "pons-dot-family": { id: "pons", label: "Pons" },
  "bankr-robinhood": { id: "bankr", label: "Bankr" },
  "clanker-robinhood": { id: "clanker", label: "Clanker" },
  "virtuals-robinhood": { id: "virtuals", label: "Virtuals" },
  hoodit: { id: "hoodit", label: "Hoodit" },
  "o1-launchpad-robinhood": { id: "o1", label: "O1" },
  "mint-club-robinhood": { id: "mint-club", label: "Mint Club" },
  "easya-kickstart-robinhood": { id: "easya", label: "EasyA Kickstart" },
  "pump-fun": { id: "pumpfun", label: "Pump.fun" },
  pumpswap: { id: "pumpfun", label: "Pump.fun" },
  "letsbonk-fun": { id: "letsbonk", label: "LetsBonk" },
  "raydium-launchlab": { id: "launchlab", label: "Raydium LaunchLab" },
  "bags-fm": { id: "bags", label: "Bags" },
  stonkfun: { id: "stonkfun", label: "Stonk.fun" },
  "boop-fun": { id: "boop", label: "Boop" },
  moonshot: { id: "moonshot", label: "Moonshot" },
  moonit: { id: "moonshot", label: "Moonshot" },
  heaven: { id: "heaven", label: "Heaven" },
  "meteora-dbc": { id: "meteora-dbc", label: "Meteora DBC" },
  clanker: { id: "clanker", label: "Clanker" },
  "virtuals-base": { id: "virtuals", label: "Virtuals" },
  "zora-base": { id: "zora", label: "Zora" },
  "four-meme": { id: "four-meme", label: "Four.meme" }
};
var MINT_SUFFIX = [
  ["pump", { id: "pumpfun", label: "Pump.fun" }],
  ["bonk", { id: "letsbonk", label: "LetsBonk" }],
  ["bags", { id: "bags", label: "Bags" }],
  ["stonk", { id: "stonkfun", label: "Stonk.fun" }],
  ["ansem", { id: "ansem", label: "Ansem" }],
  ["moon", { id: "moonshot", label: "Moonshot" }],
  ["boop", { id: "boop", label: "Boop" }]
];
var DIRECT_LAUNCH = { id: "direct", label: "Direct / DEX" };
var MAJOR_QUOTES = /* @__PURE__ */ new Set([
  "SOL",
  "WSOL",
  "USDC",
  "USDT",
  "USDG",
  "USD1",
  "PYUSD",
  "ETH",
  "WETH",
  "WBNB",
  "BNB",
  "DAI",
  "USDS"
]);
function pairLaunch(quote) {
  const q = (quote || "").trim();
  if (!q || MAJOR_QUOTES.has(q.toUpperCase())) return void 0;
  if (isStockTicker(q)) return { id: "pair:stocks", label: "Stock pair" };
  return { id: `pair:${q.toLowerCase()}`, label: `${q} pair` };
}
function isStockTicker(symbol) {
  const s = symbol.trim();
  return STOCK_TICKERS.has(s.toUpperCase()) || STOCK_TICKERS.has(s.replace(/[a-z]+$/, "").toUpperCase());
}
function launchpadFromDexIds(dexIds) {
  for (const id of dexIds) {
    const hit = DEX_TO_LAUNCHPAD[id];
    if (hit) return hit;
  }
  return void 0;
}
function launchpadFromMint(mint) {
  if (!mint || mint.startsWith("0x")) return void 0;
  const lower = mint.toLowerCase();
  return MINT_SUFFIX.find(([suffix]) => lower.endsWith(suffix))?.[1];
}
var STOCK_TICKERS = /* @__PURE__ */ new Set([
  "SPY",
  "QQQ",
  "META",
  "TSLA",
  "NVDA",
  "AAPL",
  "AMZN",
  "GOOGL",
  "GOOG",
  "MSFT",
  "HOOD",
  "AMC",
  "GME",
  "COIN",
  "MSTR",
  "SGOV",
  "PLTR",
  "NFLX",
  "AMD",
  "INTC",
  "BABA",
  "DIS",
  "UBER",
  "CRCL",
  "IWM",
  "DIA",
  "TLT",
  "GLD",
  "SLV",
  "ARKK",
  "SOFI",
  "RDDT",
  "SMCI",
  "AVGO",
  "ORCL"
]);
var NARRATIVES = [
  {
    tag: "Stonks",
    test: ({ symbol, name, quote }) => quote !== "" && isStockTicker(quote) || /stonk|stock/i.test(`${symbol} ${name} ${quote}`)
  },
  { tag: "NEAR", test: ({ symbol, name, quote }) => /near/i.test(`${symbol} ${name} ${quote}`) },
  {
    tag: "Privacy",
    test: ({ symbol, name, quote }) => /\b(w?zec|w?xmr)\b|zcash|monero|privacy/i.test(`${symbol} ${name} ${quote}`)
  },
  { tag: "Muse", test: ({ symbol, name, quote }) => /muse/i.test(`${symbol} ${name} ${quote}`) },
  {
    tag: "AI / agents",
    test: ({ symbol, name }) => /\b(ai|gpt|agents?|llm)\b|bot|402/i.test(`${symbol} ${name}`)
  },
  {
    tag: "RWA / tokenization",
    test: ({ symbol, name }) => /tokeniz|rwa|debt|treasur|bond|yield/i.test(`${symbol} ${name}`)
  },
  {
    tag: "Animals",
    test: ({ symbol, name, quote }) => /dog|doge|cat|bear|frog|pepe|\bape\b|monkey|bull|penguin|inu|shib|wif|bonk|kat\b/i.test(
      `${symbol} ${name} ${quote}`
    )
  },
  {
    tag: "CT figures",
    test: ({ symbol, name }) => /ansem|vlad|tenev|elon|trump|saylor|cz\b/i.test(`${symbol} ${name}`)
  }
];
function narrativesFor(input) {
  const t = { symbol: input.symbol || "", name: input.name || "", quote: input.quote || "" };
  const tags = NARRATIVES.filter((n) => n.test(t)).map((n) => n.tag);
  return tags.length ? tags : ["Other"];
}

// src/lib/launchpad/gecko.ts
var GT = "https://api.geckoterminal.com/api/v2/networks";
var NETWORK = {
  solana: "solana",
  robinhood: "robinhood",
  base: "base",
  ethereum: "eth",
  bnb: "bsc"
};
var cache = /* @__PURE__ */ new Map();
function quoteFromPoolName(poolName, symbol) {
  if (!poolName) return void 0;
  const sides = poolName.split("/").map((s) => s.trim().split(/\s+/)[0]);
  if (sides.length < 2) return void 0;
  const other = sides.find((s) => s.toLowerCase() !== symbol.toLowerCase());
  return other || sides[1];
}
function metaFromGecko(token, pools) {
  const symbol = token.attributes?.symbol || "";
  const name = token.attributes?.name || "";
  const top = (token.relationships?.top_pools?.data ?? []).map((p) => pools.get(p.id)).filter((p) => Boolean(p));
  const dexIds = top.map((p) => p.relationships?.dex?.data?.id || "").filter(Boolean);
  const quote = quoteFromPoolName(top[0]?.attributes?.name, symbol);
  const launchpad = launchpadFromDexIds(dexIds) || launchpadFromMint(token.attributes?.address) || pairLaunch(quote) || DIRECT_LAUNCH;
  return { launchpad, quote, name, narratives: narrativesFor({ symbol, name, quote }) };
}
var key = (chain, address) => `${chain}:${address.toLowerCase()}`;
async function fetchTokenMeta(requests, fetchFn = fetch, deadlineAt = Number.POSITIVE_INFINITY) {
  const out = /* @__PURE__ */ new Map();
  const byNetwork = /* @__PURE__ */ new Map();
  for (const r of requests) {
    if (!r.address) continue;
    const k = key(String(r.chain), r.address);
    const hit = cache.get(k);
    if (hit) {
      out.set(r.address.toLowerCase(), hit);
      continue;
    }
    const net = NETWORK[r.chain];
    if (!net) continue;
    const list = byNetwork.get(net) ?? [];
    if (!list.some((x) => x.address.toLowerCase() === r.address.toLowerCase())) list.push(r);
    byNetwork.set(net, list);
  }
  for (const [net, list] of byNetwork) {
    for (let i = 0; i < list.length; i += 30) {
      const chunk = list.slice(i, i + 30);
      if (Date.now() > deadlineAt) break;
      try {
        const url = `${GT}/${net}/tokens/multi/${chunk.map((c) => c.address).join(",")}?include=top_pools`;
        let res = await fetchFn(url, { signal: AbortSignal.timeout(12e3), headers: { accept: "application/json" } });
        for (let attempt = 1; res.status === 429 && attempt <= 2 && Date.now() + 2500 * attempt < deadlineAt; attempt++) {
          await new Promise((r) => setTimeout(r, 2500 * attempt));
          res = await fetchFn(url, { signal: AbortSignal.timeout(12e3), headers: { accept: "application/json" } });
        }
        if (!res.ok) continue;
        const body = await res.json();
        const pools = new Map((body.included ?? []).map((p) => [p.id, p]));
        for (const t of body.data ?? []) {
          const addr = t.attributes?.address?.toLowerCase();
          if (!addr) continue;
          const meta = metaFromGecko(t, pools);
          const req = chunk.find((c) => c.address.toLowerCase() === addr);
          cache.set(key(String(req?.chain ?? net), addr), meta);
          out.set(addr, meta);
        }
      } catch {
      }
    }
  }
  for (const r of requests) {
    const addr = r.address?.toLowerCase();
    if (!addr || out.has(addr)) continue;
    const launchpad = launchpadFromMint(r.address);
    if (launchpad) {
      out.set(addr, { launchpad, narratives: narrativesFor({ symbol: r.symbol }) });
    }
  }
  return out;
}

// src/lib/wallet/drip.ts
var RPC_URLS = ["https://solana-rpc.publicnode.com", "https://api.mainnet-beta.solana.com"];
var DRIP_TTL_MS = 10 * 6e4;
function classifyTx(tx, owner, mint) {
  const keys = tx.transaction.message.accountKeys.map((k) => k.pubkey);
  const payer = keys[0] || "";
  const meta = tx.meta;
  if (!meta || meta.err) return { kind: "none", amount: 0, payer, recipients: 0 };
  const deltas = /* @__PURE__ */ new Map();
  const note = (rows, sign) => {
    for (const b of rows ?? []) {
      const k = `${b.mint}|${b.owner ?? ""}`;
      deltas.set(k, (deltas.get(k) ?? 0) + sign * Number(b.uiTokenAmount.uiAmount ?? 0));
    }
  };
  note(meta.preTokenBalances, -1);
  note(meta.postTokenBalances, 1);
  let mine = 0;
  let spentOther = false;
  let gainedOther = false;
  let recipients = 0;
  for (const [k, d] of deltas) {
    const [m, o] = k.split("|");
    if (m === mint && d > 1e-12) recipients += 1;
    if (o !== owner || Math.abs(d) < 1e-12) continue;
    if (m === mint) mine += d;
    else if (d < 0) spentOther = true;
    else gainedOther = true;
  }
  const i = keys.indexOf(owner);
  if (i >= 0) {
    const lamports = (meta.postBalances[i] ?? 0) - (meta.preBalances[i] ?? 0);
    if (lamports < -1e5) spentOther = true;
    if (lamports > 1e5) gainedOther = true;
  }
  if (mine > 0) return { kind: spentOther ? "buy" : "receipt", amount: mine, payer, recipients };
  if (mine < 0) return { kind: gainedOther ? "sell" : "out", amount: -mine, payer, recipients };
  return { kind: "none", amount: 0, payer, recipients };
}
function summarize(mint, rows) {
  const stats = {
    mint,
    kind: "trade",
    receipts: 0,
    receivedAmount: 0,
    buys: 0,
    boughtAmount: 0,
    sells: 0,
    soldAmount: 0,
    windowDays: 0,
    payers: []
  };
  const payers = /* @__PURE__ */ new Map();
  let oldest = Infinity;
  for (const { cls, at } of rows) {
    if (at) oldest = Math.min(oldest, at * 1e3);
    if (cls.kind === "receipt") {
      stats.receipts += 1;
      stats.receivedAmount += cls.amount;
      payers.set(cls.payer, (payers.get(cls.payer) ?? 0) + 1);
    } else if (cls.kind === "buy") {
      stats.buys += 1;
      stats.boughtAmount += cls.amount;
    } else if (cls.kind === "sell" || cls.kind === "out") {
      stats.sells += 1;
      stats.soldAmount += cls.amount;
    }
  }
  stats.windowDays = Number.isFinite(oldest) ? Math.max(1 / 24, (Date.now() - oldest) / 864e5) : 0;
  stats.payers = [...payers.entries()].sort((a, b) => b[1] - a[1]).map(([p]) => p).slice(0, 5);
  if (stats.receipts >= 2) stats.kind = stats.buys > 0 ? "mixed" : "drip";
  return stats;
}
async function rpcBatch(calls, fetchFn) {
  const body = JSON.stringify(calls.map((c, id) => ({ jsonrpc: "2.0", id, method: c.method, params: c.params })));
  let lastErr;
  for (const url of RPC_URLS) {
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const res = await fetchFn(url, {
          method: "POST",
          headers: { "content-type": "application/json" },
          body,
          signal: AbortSignal.timeout(2e4)
        });
        if (res.status === 429) {
          lastErr = new Error("RPC 429");
          await new Promise((r) => setTimeout(r, 1200 * (attempt + 1)));
          continue;
        }
        if (!res.ok) throw new Error(`RPC ${res.status}`);
        const rows = await res.json();
        const out = calls.map(() => null);
        for (const r of Array.isArray(rows) ? rows : []) out[r.id] = r.result ?? null;
        return out;
      } catch (err) {
        lastErr = err;
      }
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error("Solana RPC batch failed");
}
var cache2 = /* @__PURE__ */ new Map();
async function analyzeMint(owner, mint, fetchFn, sigLimit) {
  const key2 = `${owner}:${mint}`;
  const hit = cache2.get(key2);
  if (hit && Date.now() - hit.at < DRIP_TTL_MS) return hit.stats;
  const [accts] = await rpcBatch(
    [{ method: "getTokenAccountsByOwner", params: [owner, { mint }, { encoding: "jsonParsed" }] }],
    fetchFn
  );
  const account = [...accts?.value ?? []].sort(
    (a, b) => Number(b.account.data.parsed.info.tokenAmount.uiAmount ?? 0) - Number(a.account.data.parsed.info.tokenAmount.uiAmount ?? 0)
  )[0]?.pubkey;
  if (!account) return summarize(mint, []);
  const [sigs] = await rpcBatch(
    [{ method: "getSignaturesForAddress", params: [account, { limit: sigLimit }] }],
    fetchFn
  );
  const rows = [];
  const list = sigs ?? [];
  for (let i = 0; i < list.length; i += 25) {
    const chunk = list.slice(i, i + 25);
    const txs = await rpcBatch(
      chunk.map((s) => ({
        method: "getTransaction",
        params: [s.signature, { encoding: "jsonParsed", maxSupportedTransactionVersion: 0 }]
      })),
      fetchFn
    );
    txs.forEach((tx, j) => {
      if (tx) rows.push({ cls: classifyTx(tx, owner, mint), at: tx.blockTime ?? chunk[j].blockTime });
    });
  }
  const stats = summarize(mint, rows);
  cache2.set(key2, { at: Date.now(), stats });
  return stats;
}
async function analyzeDrips(owner, mints, fetchFn = fetch, sigLimit = 25, deadlineAt = Number.POSITIVE_INFINITY) {
  const out = /* @__PURE__ */ new Map();
  const queue = [...new Set(mints)];
  const failed = [];
  const worker = async () => {
    for (let mint = queue.shift(); mint && Date.now() < deadlineAt; mint = queue.shift()) {
      try {
        out.set(mint, await analyzeMint(owner, mint, fetchFn, sigLimit));
      } catch {
        failed.push(mint);
      }
    }
  };
  await Promise.all([worker(), worker()]);
  for (const mint of failed) {
    if (Date.now() + 4e3 > deadlineAt) break;
    await new Promise((r) => setTimeout(r, 1500));
    try {
      out.set(mint, await analyzeMint(owner, mint, fetchFn, sigLimit));
    } catch {
    }
  }
  return out;
}

// src/lib/portfolio/load.ts
var DUST_USD2 = 5;
var WSOL3 = "So11111111111111111111111111111111111111112";
function marketFor(mint, markets) {
  if (!mint) return void 0;
  return markets.get(mint) || markets.get(mint.toLowerCase());
}
function withMarketMove(p, markets) {
  const market = marketFor(p.mint, markets);
  const currentPrice = market?.priceUsd || p.currentPrice || 0;
  const amount = p.amount || 0;
  const sizeUsd = currentPrice > 0 && amount > 0 ? currentPrice * amount : p.sizeUsd;
  const change24hPct = p.change24hPct ?? market?.change24hPct;
  const currentMcap = market?.marketCapUsd || p.currentMcap || 0;
  const entryMcap = p.entryMcap || (p.hasCostBasis ? inferredEntryMcap(currentMcap, p.entryPrice, currentPrice) : 0);
  const cost = p.hasCostBasis && p.entryPrice > 0 && amount > 0 ? p.entryPrice * amount : 0;
  const unrealizedPnl = cost > 0 && currentPrice > 0 ? (currentPrice - p.entryPrice) * amount : p.unrealizedPnl;
  const unrealizedPnlPct = cost > 0 ? unrealizedPnl / cost * 100 : p.unrealizedPnlPct;
  const pnl24hUsd = change24hPct != null ? pnlFromChangePct(sizeUsd, change24hPct) : p.pnl24hUsd;
  return {
    ...p,
    sizeUsd,
    currentPrice: currentPrice || p.currentPrice,
    currentMcap,
    entryMcap,
    unrealizedPnl,
    unrealizedPnlPct,
    liquidityUsd: p.liquidityUsd || market?.liquidityUsd,
    change24hPct,
    pnl24hUsd,
    volume24hUsd: p.volume24hUsd ?? market?.volume24hUsd
  };
}
function tokenField(row) {
  if (row.token && typeof row.token === "object") {
    return {
      symbol: row.token.symbol || row.symbol || "UNKNOWN",
      address: row.token.address || row.token.mint || row.tokenAddress
    };
  }
  return {
    symbol: row.symbol || (typeof row.token === "string" ? row.token : "UNKNOWN"),
    address: row.tokenAddress
  };
}
function isOpenRow(row) {
  const s = (row.status || "").toLowerCase();
  if (s === "closed" || s === "exited" || Boolean(row.closedAt)) return false;
  return true;
}
function mapOpenPosition(row, markets) {
  const token = tokenField(row);
  const amount = asNumber(row.amount);
  const entry = asNumber(row.avgEntryPrice);
  const livePrice = asNumber(row.priceUsd) || marketFor(token.address, markets)?.priceUsd || asNumber(row.avgExitPrice);
  const cost = asNumber(row.costBasisUsd) || (entry > 0 && amount > 0 ? entry * amount : 0);
  const mtm = livePrice > 0 && amount > 0 ? livePrice * amount : cost;
  const sizeUsd = mtm || cost;
  if (sizeUsd < DUST_USD2 && asNumber(row.unrealizedPnlUsd) === 0) return null;
  const hasCostBasis = entry > 0 && cost > 0;
  const unrealized = livePrice > 0 && entry > 0 && amount > 0 ? (livePrice - entry) * amount : asNumber(row.unrealizedPnlUsd);
  const market = marketFor(token.address, markets);
  const opened = row.createdAt || row.openedAt || (/* @__PURE__ */ new Date()).toISOString();
  const currentPrice = livePrice || entry;
  const currentMcap = asNumber(row.marketCapUsd) || market?.marketCapUsd || 0;
  return {
    id: row.tradeId || row.id || `${token.symbol}-${opened}`,
    token: token.symbol,
    symbol: token.symbol,
    mint: token.address,
    chain: normalizeChain(row.chain, row.networkId ?? (typeof row.token === "object" ? row.token.networkId : void 0)),
    sizeUsd,
    amount,
    entryPrice: entry,
    currentPrice,
    entryMcap: asNumber(row.entryMarketCapUsd) || inferredEntryMcap(currentMcap, entry, currentPrice),
    currentMcap,
    unrealizedPnl: unrealized,
    unrealizedPnlPct: cost > 0 ? unrealized / cost * 100 : 0,
    holdTimeHours: hoursBetween(opened),
    entryDate: opened,
    thesis: row.thesis,
    liquidityUsd: asNumber(row.liquidityUsd) || market?.liquidityUsd || void 0,
    source: "fomo",
    hasCostBasis,
    change24hPct: market?.change24hPct,
    pnl24hUsd: market?.change24hPct != null ? pnlFromChangePct(sizeUsd, market.change24hPct) : void 0,
    volume24hUsd: market?.volume24hUsd
  };
}
function mapClosedTrade(row) {
  const token = tokenField(row);
  const entry = asNumber(row.avgEntryPrice);
  const exit = asNumber(row.avgExitPrice);
  const cost = asNumber(row.costBasisUsd);
  const pnl = asNumber(row.realizedPnlUsd);
  const sizeUsd = cost || (entry > 0 && asNumber(row.boughtAmount) > 0 ? entry * asNumber(row.boughtAmount) : Math.abs(pnl));
  const opened = row.createdAt || row.openedAt || row.closedAt || (/* @__PURE__ */ new Date()).toISOString();
  const closed = row.closedAt || opened;
  if (!token.symbol) return null;
  return {
    id: row.tradeId || row.id || `${token.symbol}-${closed}`,
    token: token.symbol,
    symbol: token.symbol,
    mint: token.address,
    chain: normalizeChain(row.chain, row.networkId ?? (typeof row.token === "object" ? row.token.networkId : void 0)),
    side: "long",
    sizeUsd,
    entryPrice: entry,
    exitPrice: exit,
    realizedPnl: pnl,
    realizedPnlPct: sizeUsd > 0 ? pnl / sizeUsd * 100 : 0,
    holdTimeHours: hoursBetween(opened, closed),
    entryDate: opened,
    exitDate: closed
  };
}
function holdingSymbol(h) {
  if (h.token) {
    return {
      symbol: h.token.symbol || h.symbol || "UNKNOWN",
      address: h.token.address || h.token.mint || h.address,
      chain: h.chain,
      networkId: h.token.networkId ?? h.networkId
    };
  }
  return {
    symbol: h.symbol || "UNKNOWN",
    address: h.address,
    chain: h.chain,
    networkId: h.networkId
  };
}
function mapHoldingToPosition(h, markets) {
  const tok = holdingSymbol(h);
  const market = marketFor(tok.address, markets);
  const amount = asNumber(h.amount);
  const price = asNumber(h.priceUsd) || market?.priceUsd || 0;
  const value = asNumber(h.valueUsd) || amount * price;
  if (value < DUST_USD2) return null;
  const change24hPct = h.change24h != null && h.change24h !== void 0 ? asNumber(h.change24h) : market?.change24hPct;
  const pnl24hUsd = change24hPct != null ? pnlFromChangePct(value, change24hPct) : void 0;
  return {
    id: `bal-${tok.address || tok.symbol}`,
    token: tok.symbol,
    symbol: tok.symbol,
    mint: tok.address,
    chain: normalizeChain(tok.chain, tok.networkId),
    sizeUsd: value,
    amount,
    entryPrice: 0,
    currentPrice: price,
    entryMcap: 0,
    currentMcap: market?.marketCapUsd || asNumber(h.marketCapUsd),
    unrealizedPnl: pnl24hUsd ?? 0,
    unrealizedPnlPct: change24hPct || 0,
    holdTimeHours: 0,
    entryDate: (/* @__PURE__ */ new Date()).toISOString(),
    liquidityUsd: market?.liquidityUsd || asNumber(h.liquidityUsd) || void 0,
    source: "fomo",
    hasCostBasis: false,
    change24hPct: change24hPct || void 0,
    pnl24hUsd
  };
}
function mapOnchainPosition(h, markets, solPrice) {
  const market = marketFor(h.mint, markets);
  const price = h.priceUsd ?? market?.priceUsd ?? (h.mint === WSOL3 || h.native ? solPrice : 0);
  const value = h.valueUsd ?? (price > 0 ? h.amount * price : 0);
  if (value < DUST_USD2) return null;
  const symbol = h.symbol || market?.symbol || h.mint.slice(0, 6);
  const change24hPct = market?.change24hPct;
  const pnl24hUsd = change24hPct != null ? pnlFromChangePct(value, change24hPct) : void 0;
  return {
    id: `onchain-${h.mint}`,
    token: symbol,
    symbol,
    mint: h.mint,
    chain: "solana",
    sizeUsd: value,
    amount: h.amount,
    entryPrice: 0,
    currentPrice: price,
    entryMcap: 0,
    currentMcap: market?.marketCapUsd || 0,
    unrealizedPnl: pnl24hUsd ?? 0,
    unrealizedPnlPct: change24hPct ?? 0,
    holdTimeHours: 0,
    entryDate: (/* @__PURE__ */ new Date()).toISOString(),
    liquidityUsd: market?.liquidityUsd,
    source: "onchain",
    hasCostBasis: false,
    change24hPct,
    pnl24hUsd,
    volume24hUsd: market?.volume24hUsd
  };
}
function mergePositions(fomo, onchain) {
  const byMint = /* @__PURE__ */ new Map();
  const noMint = [];
  for (const p of fomo) {
    if (p.mint) byMint.set(p.mint.toLowerCase(), p);
    else noMint.push(p);
  }
  for (const p of onchain) {
    if (!p.mint) {
      noMint.push(p);
      continue;
    }
    const key2 = p.mint.toLowerCase();
    const existing = byMint.get(key2);
    if (!existing) {
      byMint.set(key2, p);
      continue;
    }
    byMint.set(key2, {
      ...existing,
      sizeUsd: Math.max(existing.sizeUsd, p.sizeUsd),
      amount: p.amount || existing.amount,
      currentPrice: p.currentPrice || existing.currentPrice,
      currentMcap: p.currentMcap || existing.currentMcap,
      liquidityUsd: existing.liquidityUsd || p.liquidityUsd,
      change24hPct: p.change24hPct ?? existing.change24hPct,
      pnl24hUsd: p.pnl24hUsd ?? existing.pnl24hUsd,
      volume24hUsd: p.volume24hUsd ?? existing.volume24hUsd,
      thesis: existing.thesis || p.thesis,
      hasCostBasis: Boolean(existing.hasCostBasis || p.hasCostBasis),
      source: existing.hasCostBasis || existing.source === "fomo" ? "merged" : p.source
    });
  }
  return [...byMint.values(), ...noMint];
}
function splitCash(positions) {
  const cash = [];
  const risk = [];
  for (const p of positions) {
    if (isCashAsset(p.symbol, p.mint)) cash.push(p);
    else risk.push(p);
  }
  return { cash, risk };
}
function findRank(traders, handle) {
  const h = handle.replace(/^@/, "").toLowerCase();
  return traders?.find((t) => (t.handle || "").replace(/^@/, "").toLowerCase() === h)?.rank;
}
async function tagLaunchpads(open, closed, markets, fetchFn, deadlineAt) {
  const requests = [...open, ...closed].filter((p) => p.mint).map((p) => ({ address: p.mint, chain: p.chain, symbol: p.symbol }));
  let meta = /* @__PURE__ */ new Map();
  try {
    meta = await fetchTokenMeta(requests, fetchFn, deadlineAt);
  } catch {
  }
  for (const row of [...open, ...closed]) {
    const m = row.mint ? meta.get(row.mint.toLowerCase()) : void 0;
    if (!m) {
      const quote = marketFor(row.mint, markets)?.quoteSymbol;
      if (!quote) continue;
      const pad = pairLaunch(quote);
      if (pad) {
        row.launchpad = pad.label;
        row.launchpadId = pad.id;
      }
      row.narratives = narrativesFor({ symbol: row.symbol, quote });
      if ("currentPrice" in row) row.quoteSymbol = quote;
      continue;
    }
    row.launchpad = m.launchpad.label;
    row.launchpadId = m.launchpad.id;
    row.narratives = m.narratives;
    if ("currentPrice" in row) row.quoteSymbol = m.quote;
  }
}
function symbolKey(s) {
  return (s || "").toLowerCase().replace(/^\$/, "");
}
function sameAsset(a, b) {
  const x = symbolKey(a);
  const y = symbolKey(b);
  return Boolean(x && y) && (x === y || x === `w${y}` || `w${x}` === y);
}
async function tagDrips(open, owner, fetchFn, analyze = analyzeDrips) {
  const sol = open.filter((p) => p.chain === "solana" && p.mint);
  const payersOf = (reward) => sol.filter((t) => t !== reward && sameAsset(t.quoteSymbol, reward.symbol));
  const candidates = sol.filter((p) => payersOf(p).length > 0).sort((a, b) => b.sizeUsd - a.sizeUsd).slice(0, 6);
  let stats = /* @__PURE__ */ new Map();
  if (candidates.length) {
    try {
      stats = await analyze(owner, candidates.map((p) => p.mint), fetchFn);
    } catch {
    }
  }
  for (const reward of candidates) {
    const s = stats.get(reward.mint);
    if (!s || s.kind === "trade") continue;
    const unit = reward.amount && reward.amount > 0 ? reward.sizeUsd / reward.amount : reward.currentPrice;
    const receivedUsd = s.receivedAmount * (unit || 0);
    const perDay = s.windowDays > 0 ? receivedUsd / s.windowDays : 0;
    const sources = payersOf(reward);
    reward.strategy = "drip-reward";
    reward.dripReceipts = s.receipts;
    reward.dripReceivedUsd = receivedUsd;
    reward.dripPerDayUsd = perDay;
    reward.dripFrom = sources.map((t) => t.symbol);
    const total = sources.reduce((sum, t) => sum + t.sizeUsd, 0) || 1;
    for (const t of sources) {
      t.strategy = "drip-pair";
      t.dripPays = reward.symbol;
      t.dripPerDayUsd = (t.dripPerDayUsd ?? 0) + perDay * (t.sizeUsd / total);
    }
  }
  for (const p of open) p.strategy = p.strategy ?? "trade";
}
var RELAY_BUDGET_MS = 22e3;
var TAGS_BUDGET_MS = 38e3;
var DRIP_BUDGET_MS = 5e4;
async function loadPortfolio(input) {
  const startedAt = Date.now();
  const handle = input.handle?.replace(/^@/, "").trim();
  const fetchFn = input.fetchFn ?? fetch;
  const warnings = [];
  let user = null;
  let searchHit = null;
  let fomoPositions = [];
  let fomoHoldings = [];
  let relayOpen = [];
  let relayClosed = [];
  let closedTotalOnFomo;
  let livePerpPnl = 0;
  let fomoTotalValue;
  let fomoOk = false;
  let rank;
  let solanaWallet = input.solanaWallet?.trim() || void 0;
  let evmWallet = input.evmWallet?.trim() || void 0;
  let onchainPromise;
  const startOnchain = () => {
    if (onchainPromise || !solanaWallet) return;
    onchainPromise = fetchSolanaHoldings({
      owner: solanaWallet,
      rpcUrl: input.solanaRpcUrl,
      heliusApiKey: input.heliusApiKey,
      fetchFn
    });
  };
  let fomoOutOfCredits = false;
  if (handle && input.apiKey) {
    const client = createFomoClient({ apiKey: input.apiKey, fetchFn });
    try {
      const found = await client.search(handle);
      const rows = found.results ?? found.traders ?? [];
      searchHit = rows.find(
        (r) => (r.handle || "").replace(/^@/, "").toLowerCase() === handle.toLowerCase()
      ) ?? rows[0] ?? null;
      if (searchHit?.wallets?.solana) solanaWallet = solanaWallet || searchHit.wallets.solana;
      if (searchHit?.wallets?.evm) evmWallet = evmWallet || searchHit.wallets.evm;
      if (searchHit?.handle) fomoOk = true;
      startOnchain();
    } catch (err) {
      if (err instanceof FomoApiError && err.code === "auth") {
        warnings.push("FOMO API key rejected (401). Check FOMO_API_KEY.");
      } else if (err instanceof FomoApiError && err.code === "credits") {
        fomoOutOfCredits = true;
        warnings.push(
          "fomoapi.io is out of credits (402). Top up at fomoapi.io/pricing, or paste your Solana wallet in Sources so the wallet path can still mark the book."
        );
      } else {
        warnings.push(`Search: ${err instanceof Error ? err.message : "failed"}`);
      }
    }
  }
  if (handle && input.apiKey && !fomoOutOfCredits) {
    const client = createFomoClient({ apiKey: input.apiKey, fetchFn });
    const fomoKey = searchHit?.userId || handle;
    const results = await Promise.allSettled([
      client.resolveUser(handle),
      client.positions(fomoKey),
      client.balances(fomoKey),
      client.leaderboard("all"),
      client.spotlight(handle),
      client.relaySwaps(handle)
    ]);
    const take = (i, label) => {
      const r = results[i];
      if (r.status === "fulfilled") return r.value;
      const err = r.reason;
      if (err instanceof FomoApiError) {
        if (err.code === "auth") warnings.push("FOMO API key rejected (401). Check FOMO_API_KEY.");
        else if (err.code === "credits") warnings.push("FOMO API credits exhausted (402). Wallet path still runs.");
        else if (err.code === "not_found") warnings.push(`FOMO handle @${handle} was not found.`);
        else warnings.push(`${label}: ${err.message}`);
      } else {
        warnings.push(`${label}: ${err instanceof Error ? err.message : "failed"}`);
      }
      return null;
    };
    user = take(0, "Profile");
    const pos = take(1, "Positions");
    const bal = take(2, "Balances");
    const board = take(3, "Leaderboard");
    const spot = take(4, "Spotlight");
    const relay = take(5, "Relay");
    if (user && !user.error) fomoOk = true;
    if (user?.wallets?.solana) solanaWallet = solanaWallet || user.wallets.solana;
    if (user?.wallets?.evm || user?.wallets?.ethereum) {
      evmWallet = evmWallet || user.wallets.evm || user.wallets.ethereum || void 0;
    }
    startOnchain();
    if (pos) {
      fomoPositions = pos.positions ?? pos.trades ?? pos.items ?? [];
      closedTotalOnFomo = pos.closedTotalOnFomo;
      if (pos.available === false && !fomoPositions.length) {
        warnings.push("FOMO has not captured the full trade tape for this handle yet.");
      }
    }
    if (spot?.bestTrades?.length) {
      fomoPositions = [...fomoPositions, ...spot.bestTrades];
    }
    if (relay?.swaps?.length) {
      relayOpen = positionsFromRelaySwaps(relay.swaps);
    }
    if (bal) {
      fomoHoldings = bal.holdings ?? bal.balances ?? [];
      fomoTotalValue = bal.totalValueUsd;
      const perp = bal.livePerpPnl;
      livePerpPnl = typeof perp === "number" ? perp : asNumber(perp?.usd);
      if (bal.available === false && !fomoHoldings.length) {
        warnings.push("FOMO holdings feed is empty; using wallet + Relay marks.");
      }
    }
    rank = findRank(board?.traders, handle);
  } else if (handle && !input.apiKey) {
    warnings.push("Set FOMO_API_KEY (or paste a key in Settings) to pull FOMO PnL, trades, and social stats.");
  } else if (!handle) {
    warnings.push("No FOMO handle set \u2014 running wallet / on-chain path only.");
  }
  let onchain = [];
  let onchainOk = false;
  startOnchain();
  const relayUser = solanaWallet || evmWallet;
  const relayPromise = relayUser ? fetchRelayHistory(relayUser, fetchFn, 8, startedAt + RELAY_BUDGET_MS) : void 0;
  let relayOk = false;
  if (relayPromise) {
    try {
      const history = await relayPromise;
      if (history.swaps.length) {
        relayOpen = positionsFromRelaySwaps(history.swaps);
        relayClosed = closedFromRelaySwaps(history.swaps);
        relayOk = true;
      }
      evmWallet = evmWallet || history.evmWallet;
      if (history.truncated) {
        warnings.push("Relay history was cut short (long history or rate limit); bags bought before the loaded window may be missing.");
      }
    } catch (err) {
      warnings.push(`Relay history: ${err instanceof Error ? err.message : "failed"}`);
    }
  }
  if (onchainPromise) {
    try {
      onchain = await onchainPromise;
      onchainOk = true;
    } catch (err) {
      warnings.push(
        `Solana wallet read failed: ${err instanceof Error ? err.message : "RPC error"}`
      );
    }
  } else {
    warnings.push("No Solana wallet yet. Paste the address in Sources (or set SOLANA_WALLET) so the book loads even when FOMO is down.");
  }
  const mints = [
    ...fomoPositions.map((p) => tokenField(p).address),
    ...fomoHoldings.map((h) => holdingSymbol(h).address),
    ...onchain.map((h) => h.mint),
    ...relayOpen.map((p) => p.mint)
  ].filter((m) => Boolean(m));
  const [markets, solPrice] = await Promise.all([
    fetchDexMarkets(mints, fetchFn),
    fetchSolPriceUsd(fetchFn)
  ]);
  const openFromFomo = fomoPositions.filter(isOpenRow).map((p) => mapOpenPosition(p, markets)).filter((p) => Boolean(p));
  const fomoClosed = fomoPositions.filter((p) => {
    const s = (p.status || "").toLowerCase();
    return s === "closed" || Boolean(p.closedAt);
  }).map(mapClosedTrade).filter((t) => Boolean(t));
  const closed = fomoClosed.length ? fomoClosed : relayClosed;
  const fromBalances = fomoHoldings.map((h) => mapHoldingToPosition(h, markets)).filter((p) => Boolean(p));
  const fromChain = onchain.map((h) => mapOnchainPosition(h, markets, solPrice)).filter((p) => Boolean(p));
  const fromRelay = relayOpen.map((p) => withMarketMove(p, markets));
  const holdings = mergePositions(fromChain, fromRelay);
  const fomoBase = openFromFomo.length ? openFromFomo : fromBalances;
  const merged = mergePositions(fomoBase, holdings).map((p) => withMarketMove(p, markets));
  if (onchainOk && fromChain.length && openFromFomo.length > fromChain.length + 3) {
    warnings.push(
      `FOMO lists ${openFromFomo.length} open names vs ${fromChain.length} Solana tokens in the wallet \u2014 some FOMO rows can lag exits.`
    );
  }
  const { cash, risk } = splitCash(merged);
  await tagLaunchpads(risk, closed, markets, fetchFn, startedAt + TAGS_BUDGET_MS);
  if (solanaWallet && onchainOk && Date.now() < startedAt + DRIP_BUDGET_MS - 8e3) {
    await tagDrips(
      risk,
      solanaWallet,
      fetchFn,
      (owner, mints2, f) => analyzeDrips(owner, mints2, f, 25, startedAt + DRIP_BUDGET_MS)
    );
  }
  const cashUsd = cash.reduce((s, p) => s + p.sizeUsd, 0);
  const openPositionsValue = risk.reduce((s, p) => s + p.sizeUsd, 0);
  const hasCostBasis = risk.some((p) => p.hasCostBasis);
  const unrealized = risk.reduce((s, p) => s + (p.hasCostBasis ? p.unrealizedPnl : p.pnl24hUsd ?? 0), 0) + livePerpPnl;
  const pnl24h = [...cash, ...risk].reduce((s, p) => s + (p.pnl24hUsd ?? 0), 0) + livePerpPnl;
  const any24h = [...cash, ...risk].some((p) => p.pnl24hUsd != null);
  const chainTotal = [...cash, ...risk].reduce((s, p) => s + p.sizeUsd, 0);
  const totalEquity = fomoTotalValue && fomoTotalValue > 0 ? fomoTotalValue + (livePerpPnl || 0) : chainTotal || openPositionsValue + cashUsd;
  const fomoAllTime = user?.pnl?.all ?? (user?.pnlUsd == null ? null : user.pnlUsd);
  const pnlWindows = {
    h24: user?.pnl?.["24h"] ?? (any24h ? pnl24h : null),
    d7: user?.pnl?.["7d"] ?? null,
    d30: user?.pnl?.["30d"] ?? null,
    all: fomoAllTime
  };
  const closedStats = statsFromClosed(closed);
  const closedSum = closed.reduce((s, t) => s + t.realizedPnl, 0);
  const spotlightRealized = fomoPositions.reduce((s, p) => s + asNumber(p.realizedPnlUsd), 0);
  const realizedAllTime = fomoAllTime ?? (closed.length ? closedSum : spotlightRealized ? spotlightRealized : null);
  let equityCurve = buildEquityCurve(closed, totalEquity, realizedAllTime ?? 0, hasCostBasis ? unrealized : 0);
  const peakEquity = Math.max(totalEquity, ...equityCurve.map((p) => p.equity), 0);
  if (equityCurve.length < 2 && pnlWindows.h24 != null) {
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const yday = new Date(Date.now() - 864e5).toISOString().slice(0, 10);
    equityCurve = [
      { date: yday, equity: Math.max(0, totalEquity - pnlWindows.h24), realizedPnl: 0 },
      { date: today, equity: totalEquity, realizedPnl: realizedAllTime ?? 0 }
    ];
  }
  const currentDrawdownPct = drawdownPct(totalEquity, peakEquity);
  const alerts = buildAlerts(totalEquity, cashUsd, risk, currentDrawdownPct);
  const followers = asNumber(user?.followers ?? user?.profile?.followers);
  const avgHold = user?.averageHoldTimeSeconds ?? user?.profile?.averageHoldTimeSeconds;
  const volumeUsd = user?.volumeUsd ?? user?.totalVolume ?? user?.profile?.totalVolumeUsd ?? null;
  return {
    handle: user?.handle || user?.userHandle || searchHit?.handle || handle,
    displayName: user?.displayName || searchHit?.displayName,
    wallets: { solana: solanaWallet, evm: evmWallet },
    source: {
      fomo: fomoOk,
      onchain: onchainOk || relayOk,
      fetchedAt: (/* @__PURE__ */ new Date()).toISOString(),
      warnings: [...new Set(warnings)]
    },
    summary: {
      totalEquity,
      cashUsd,
      openPositionsValue,
      realizedPnlAllTime: realizedAllTime,
      realizedPnl7d: pnlWindows.d7 ?? closedStats.realized7d,
      realizedPnl30d: pnlWindows.d30 ?? closedStats.realized30d,
      unrealizedPnl: unrealized,
      volumeUsd,
      peakEquity,
      currentDrawdownPct,
      winRate: closedStats.winRate,
      profitFactor: closedStats.profitFactor,
      avgRMultiple: closedStats.avgRMultiple,
      totalTrades: closedTotalOnFomo || asNumber(user?.trades ?? user?.numTrades) || closedStats.totalTrades,
      closedTradesCaptured: closed.length,
      followers,
      leaderboardRank: rank
    },
    influence: {
      followers,
      following: user?.following ?? user?.profile?.following ?? null,
      leaderboardRank: rank,
      rankWindow: rank != null ? "all" : void 0,
      averageHoldTimeHours: avgHold != null ? avgHold / 3600 : void 0,
      accountAgeDays: user?.accountAgeDays ?? user?.profile?.accountAgeDays
    },
    pnlWindows,
    openPositions: [...risk].sort((a, b) => b.sizeUsd - a.sizeUsd),
    closedTrades: closed.sort((a, b) => Date.parse(b.exitDate) - Date.parse(a.exitDate)),
    equityCurve,
    alerts
  };
}

// server/knownWallets.ts
var KNOWN = {
  busymeredog: {
    solana: "3bkwLLEiF9uvM1c3JBnmUXrCei7r7AezC7Td2riFmfxR",
    evm: "0x06953a582f054b7b7c4c6dd890777e3958b4a673"
  },
  softmereelk: {
    solana: "Ei1dmgYK1av31iuQHzpTx4e7vAg5nXxA9mE7x1Gr34Ao",
    evm: "0x455ef47a4dd4e682b08d28bd28fdf68f1de38b81"
  }
};
function sameHandle(a, b) {
  const norm = (h) => (h || "").replace(/^@/, "").trim().toLowerCase();
  return !norm(a) || !norm(b) || norm(a) === norm(b);
}
function knownWallets(handle) {
  const row = KNOWN[(handle || "").replace(/^@/, "").toLowerCase()] ?? {};
  return { solana: row.solana || "", evm: row.evm || "" };
}

// server/vercel-portfolio.ts
var config = {
  maxDuration: 60
};
function first(value) {
  if (Array.isArray(value)) return value[0] || "";
  return value || "";
}
function headerValue(headers2, name) {
  if (headers2 && typeof headers2.get === "function") {
    return headers2.get(name) || "";
  }
  const rec = headers2;
  return first(rec[name] || rec[name.toLowerCase()]);
}
function queryValue(req, name) {
  if (req.query) return first(req.query[name]);
  try {
    const url = new URL(req.url || "", "http://localhost");
    return url.searchParams.get(name) || "";
  } catch {
    return "";
  }
}
function json(res, status, body) {
  res.setHeader?.("content-type", "application/json; charset=utf-8");
  res.setHeader?.("cache-control", "no-store");
  res.status(status).json(body);
}
async function handler(req, res) {
  try {
    if (req.method === "OPTIONS") {
      res.status(204).end();
      return;
    }
    const defaultHandle = process.env.FOMO_HANDLE || process.env.VITE_FOMO_HANDLE || "";
    const handle = queryValue(req, "handle") || defaultHandle;
    const envWallets = sameHandle(handle, defaultHandle) ? {
      solana: process.env.SOLANA_WALLET || process.env.VITE_SOLANA_WALLET || "",
      evm: process.env.EVM_WALLET || process.env.VITE_EVM_WALLET || ""
    } : { solana: "", evm: "" };
    const known = knownWallets(handle);
    const solanaWallet = queryValue(req, "solana") || envWallets.solana || known.solana || queryValue(req, "solanaHint");
    const evmWallet = queryValue(req, "evm") || envWallets.evm || known.evm || queryValue(req, "evmHint");
    const apiKey = headerValue(req.headers, "x-fomo-api-key") || process.env.FOMO_API_KEY || process.env.VITE_FOMO_API_KEY || "";
    if (!handle && !solanaWallet) {
      json(res, 400, {
        error: "config",
        message: "Set a FOMO handle and/or a Solana wallet in Settings, or FOMO_HANDLE / SOLANA_WALLET in the environment."
      });
      return;
    }
    const snapshot = await loadPortfolio({
      handle,
      apiKey,
      solanaWallet,
      evmWallet,
      solanaRpcUrl: process.env.SOLANA_RPC_URL,
      heliusApiKey: process.env.HELIUS_API_KEY
    });
    json(res, 200, snapshot);
  } catch (err) {
    json(res, 502, {
      error: "upstream",
      message: err instanceof Error ? err.message : "Failed to load portfolio"
    });
  }
}
export {
  config,
  handler as default
};
